### ISSUE TITLE
Multilang 2 translation module on slideshow description and course summary !!!

### ISSUE THREAD

**Issue by naamaan** [dbnschools/moodle-theme_fordson#100]
Hi,
I'm using Moodle 3.6 with Fordson theme and the [multilang2 translation module](https://moodle.org/plugins/filter_multilang2).
In the slideshow the module isn't translating the slide description, also the course summary when listing courses, please see the attached snapshots.

![Slideshow](https://user-images.githubusercontent.com/2176593/73434624-c2ecd600-434f-11ea-8259-7c3ef777260e.PNG)

![CourseSummury](https://user-images.githubusercontent.com/2176593/73434647-caac7a80-434f-11ea-9188-9a7d39844360.PNG)

How could I track this problem!?

Regards,

**Comment by izendegi** [comment]
Hi @naamaan 

Some time ago I found some strings that weren't formatted using the filters and did some changes to fix them here:

https://github.com/dbnschools/moodle-theme_fordson/pull/65

I guess that your issue may be similar but with other strings.

**Comment by dbnschools** [comment]
Upgrade to latest version.  We did do some work to address this in later versions of Fordson.
