### ISSUE TITLE
Notice:  Trying to get property 'cm' of non-object in lib\fordson_lib.php on line 133

### ISSUE THREAD

**Issue by gjb2048** [dbnschools/moodle-theme_fordson#102]
Ref: https://moodle.org/mod/forum/discuss.php?d=397690#p1603928

**Comment by giselebrugger** [comment]
The same erro in moodle/my
Css and fordson images are not loaded.
Moodle : Moodle 3.10.1+ (Build: 20210219)
Fordson: 
$plugin->version   = 2021020200;
$plugin->release  = 'Moodle 3.10 Fordson v3.10 release 2.1';

**Comment by gjb2048** [comment]
Should this be closed?
