### ISSUE TITLE
More details on how to customize dashbord's "user panel"

### ISSUE THREAD

**Issue by vanoir** [dbnschools/moodle-theme_fordson#103]
Hello,

I'm developing a Moodle and I'm having trouble customizing this dashboard panel (see attached image). How do I place links other than "message"? Can I choose not to show the student's full name? Where should I customize to configure this?

<img width="1440" alt="Captura de Tela 2020-03-02 às 18 40 31" src="https://user-images.githubusercontent.com/1004291/75778011-cc45d580-5d35-11ea-8a26-adf59bd0dcab.png">

**Comment by dbnschools** [comment]
I would simply use CSS to hide it on the Dashboard page if you do not need it.
`#page-my-index .header-button-group a#message-user-button {
    display: none;
}`

**Comment by vanoir** [comment]
Thanks for the quick response. Actually, I would like to add more stuff and not remove it!

**Comment by dbnschools** [comment]
If you want to add more stuff then you will have to re-write the renderer that generates that area of the page.  Offhand, I am not sure how to guide you on this.

**Comment by dbnschools** [comment]
I am going to guess you might find some luck starting with the core_renderer.php and the full_header function as a starting point.

**Comment by vanoir** [comment]
That was all the answer I needed. Thank you sir. Hopefully I will collaborate with you guys here!

**Comment by dbnschools** [comment]
We always like to see any improvements people make.  We'd love to see what you come up with.  Keep us informed.  Thanks!
