### ISSUE TITLE
Alerts only show when logged in

### ISSUE THREAD

**Issue by emmarichardson** [dbnschools/moodle-theme_fordson#104]
While I understand that your theme is based on the premise that the first thing people should do is log in, alerts should be able to be set to show all the time even when not logged in.  At least an option would be helpful...please.....

**Comment by dbnschools** [comment]
Hey Emma,
The alert should show up
- on the Fordson Custom Login page
- Site Homepage (logged in or as guest)
- Dashboard page (logged in)

Are you saying you want it everywhere?

**Comment by emmarichardson** [comment]
I just need it on the site hompage when not logged in - we don’t use the custom login page…we are using Moodle more as a regular website…yes, out of the box, I know..!

Emma

**Comment by dbnschools** [comment]
OK.  I have it so that it should appear on
- Custom Login Page
- Site Home
- Dashboard
- Standard Login Page

This should cover all the bases.  It will be in the next release.  I will push it to the github later today.

**Comment by emmarichardson** [comment]
You are awesome!  Thank you so much!

Emma

**Comment by dbnschools** [comment]
I am not quite sure why we only limited it to logged in on the dashboard and other areas.  It should just be displayed.  Good suggestion.  Thank you.

**Comment by dbnschools** [comment]
closing. 1.4 for Moodle 3.8 will have this fix.  It is now on github.
