### ISSUE TITLE
I've updated the theme code and now the "messsage" page don't have the breacrumb

### ISSUE THREAD

**Issue by vanoir** [dbnschools/moodle-theme_fordson#108]
Hello,

It looks like the message page is behaving like the dashboard page or my page.

It show the icon menu and don't have the breadcrumb. Will it be like this from now on or is it a bug? losing the breadcrumb there broke my design.

Thank you!

**Comment by vanoir** [comment]
Oh, forgot to upload the screen print: https://imgur.com/35CivL9

I remove all css customizations to make that print.

**Comment by dbnschools** [comment]
I can tell you that showing breadcrumbs works on a default setup with Moodle and Fordson theme.  This is most likely related to a plugin or some other customization you might have implemented.  It would be impossible to fix for me since I do not have all the customizations you have done.
