### ISSUE TITLE
Wrong selector in format_collapsibletopics_renderer.php causes errors

### ISSUE THREAD

**Issue by yorickreum** [dbnschools/moodle-theme_fordson#109]
Please see https://github.com/cellule-tice/moodle-format_collapsibletopics/pull/18 – this issue also affects line 298 of `classes/format_collapsibletopics_renderer.php`.
You only have to add a single "." in front "accordion", hence I did not open a pull request to merge.

**Comment by dbnschools** [comment]
Thanks. I will investigate and fix as soon as I can.

**Comment by dbnschools** [comment]
Added in 1.5 release coming out soon.
