### ISSUE TITLE
Sub-menu items in the nav-drawer

### ISSUE THREAD

**Issue by richardschwarz** [dbnschools/moodle-theme_fordson#11]
Love the theme! 
I'm only having one issue at the moment - adding submenu items in the nav-drawer, to work like the 'My Courses' section in the nav-drawer. 
I'm using the syntax of the custom menu - eg:
Student Links
-Google Drive|https;//drive.google.com/
-Office Online|https://portal.office.com

but the ones with the hyphen don't show. 
Not supported?

**Comment by dbnschools** [comment]
I'm thinking that this is more of a CSS issue and not something that the nav-drawer supports.  There are many posts in the Moodle.org forums about trying to bring in this functionality.
