### ISSUE TITLE
Activities/Resources custom menu - can specific LTI tools be added to it?

### ISSUE THREAD

**Issue by acquaalta** [dbnschools/moodle-theme_fordson#111]
Hi Chris,

Moodle version: 3.8.2
Theme Version: Moodle 3.8 Fordson v3.8 release 1.3

**Can specific LTI (External) tools be added to the custom activity chooser menu?**

- I'm using Zoom in Moodle, by using the External Tool (LTI) activity which is configured for Zoom. The tool is set to "Show in activity chooser and as a preconfigured tool".
- I enabled the "Show Only Custom Menu" setting of Fordson.
- I want to show the Zoom LTI tool in the custom activity choose menu of Fordson. Preferably, only this specific tool, but if it isn't possible, at least also it.

The strange thing is that if the specific tool is set to "Show in activity chooser and as a preconfigured tool", the tool disappears from the custom menu even when the "lti" value is included in the "Customized activity and resource modules" setting of Fordson. However, if the tool is set to "show as preconfigured tool when adding an external tool", the "External Tool" activity appears in the custom activity choose menu, but then the specific LTI tool does not appear in the custom menu, as expected.

I know that soon you will release a version of Fordson that is compatible with Moodle v3.9 with the new activity chooser, and the custom menu will not be supported anymore. I'm asking about Moodle v3.8 because I can't update to v3.9 in near future.

Thanks in advance :-)

**Comment by dbnschools** [comment]
Yes.  That is a setting on the External Tool and it appears in the listing.  I am not sure if you can only allow the external tool.  We haven't used it in that manner.  Anyways, the custom menu goes away in Moodle 3.9 with the new Moodle Activity Chooser redesign.  It's much better.
