### ISSUE TITLE
Cog icon for deleting/renaming H5P in Content Bank absent

### ISSUE THREAD

**Issue by opinco** [dbnschools/moodle-theme_fordson#112]
I just update Moodle to 3.9, donwloaded last version of Fordson.
When using the new content bank I couldn't find  this cog. According to Moodle Documentation is supposed to be top right of the page. Now I can't delete my H5P activities.
[](https://docs.moodle.org/39/en/Content_bank#Renaming_and_deleting_H5P)

**Comment by dbnschools** [comment]
Good catch!  I didn't see this during testing.  I have a fix and it will be published tomorrow.  In the meantime, you can add this to the fordson/templates/header.mustache file:
<div class="header-actions-container flex-shrink-0" data-region="header-actions-container">
     {{#headeractions}}
          <div class="header-action ml-2">{{{.}}}</div>
     {{/headeractions}}
</div>

Add this right after the 
{{/settingsmenu}}
around line 39.

**Comment by opinco** [comment]
Thank you for your swift response. However I'm still unable to see the icon. I put it where you indicated, right after the {{/settingsmenu}} and before the </div> mark.
I'll wait till the official release. Thank you again

**Comment by dbnschools** [comment]
I forgot that there was also a change needed in the core_renderer file.  Anyways, I published this as a quick fix as version 1.1 and it is on Moodle.org now and github.

**Comment by opinco** [comment]
Thank you very much. this is a fantastic theme.

**Comment by dbnschools** [comment]
Thank you for the kind words.  God Bless!
