### ISSUE TITLE
favicon breaks LTI

### ISSUE THREAD

**Issue by hartmut1s** [dbnschools/moodle-theme_fordson#114]
When I tried to set up LTI as provider with theme Fordson at our PIU DE site, I got an error message "Exception - Call to a member function out() on string." After I deleted the favicon in Fordson, I was able to connect.

See also the discussion at https://moodle.org/mod/forum/discuss.php?d=371252

**Comment by dbnschools** [comment]
We will most likely be removing this feature in an upcoming release at some point.

**Comment by dbnschools** [comment]
Part of a bigger overhaul possibly for Moodle 4.0

**Comment by hartmut1s** [comment]
Thank you for your response and for providing an excellent theme. I appreciate your efforts to maintain it.
