### ISSUE TITLE
This Course menu listing topics that are hidden from students

### ISSUE THREAD

**Issue by michael-elon** [dbnschools/moodle-theme_fordson#116]
Hi all,

We're loving Fordson at Elon. One thing an instructor on our Moodle Advisory Group uncovered is that the This Course menu lists all topics in a course, including topics that have been set to be hidden from students. I've been able to test and verify. I dug through the settings but could not find an option to restrict this. 

Steps to Replicate:

1. Ensure the Course Format settings are configured to make hidden topics invisible to students
2. Ensure there are at least two topics in the course
3. Hide one of the topics
4. Switch role to student (or have someone enrolled as a student visit your course)
5. Open the This Course menu
6. The name of the hidden topic will appear in the list

For what it's worth, clicking it will do nothing, but ideally it wouldn't display at all. 

Michael

**Comment by dbnschools** [comment]
We are thinking of removing that menu.  There was a time we thought it would be useful but have since not used it as a feature.

**Comment by michael-elon** [comment]
Understood.

I’m sure you get this a lot, but we’re really loving Fordson. The thought that went into the core features is remarkable. Our faculty are over the moon at even the more basic changes that have made their lives much easier (one click editing in the header? brilliant).

Michael
________________________________
Michael Vaughn | Instructional Technologist
Teaching and Learning Technologies | Elon University
115 Belk Library | x5032 | <file://composeviewinternalloadurl/mvaughn3@elon.edu> mvaughn3@elon.edu<file://composeviewinternalloadurl/mvaughn3@elon.edu>

Check out my website<http://www.michael-vaughn.com/>  |  Connect with me on LinkedIn<http://www.linkedin.com/in/michaelavaughn/>

He/him/his
What are personal pronouns, and why do they matter?<https://www.mypronouns.org/what-and-why/>

Looking for help or want to open a support ticket? www.elon.edu/servicedesk<http://www.elon.edu/servicedesk>





On Jul 29, 2020, at 12:50 PM, Dearborn Public Schools <notifications@github.com<mailto:notifications@github.com>> wrote:



We are thinking of removing that menu. There was a time we thought it would be useful but have since not used it as a feature.

**Comment by dbnschools** [comment]
Thank you very much for your appreciation of our work.  The editing button concept we developed should be in core.  SO many teachers who've used other themes are overjoyed when they try Fordson for that one reason alone.
