### ISSUE TITLE
Badge management links are shown in the teacher dashboard even if they are disabled

### ISSUE THREAD

**Issue by sbourget** [dbnschools/moodle-theme_fordson#119]
If badges are disabled globally (via advanced settings) the badge section on the teacher dashboard is displayed to the user.
Clicking on the links display an error.  
Shouldn't this section be hidden if badges are disabled?
![Screen Shot 2020-09-06 at 1 26 36 PM](https://user-images.githubusercontent.com/1093550/92331440-9e26b280-f044-11ea-875b-b4d99d469adc.png)
![Screen Shot 2020-09-06 at 1 27 34 PM](https://user-images.githubusercontent.com/1093550/92331458-c57d7f80-f044-11ea-95e4-f816efc080cd.png)

**Comment by dbnschools** [comment]
Turn off the permission to manage badges for the teacher role in site admin.

**Comment by sbourget** [comment]
Thanks for the work around.  In the mean time I've applied the patch (which was submitted as PR #120) which seems to have fixed the issue.
