### ISSUE TITLE
Notice: Undefined property: stdClass::$showbacktotop

### ISSUE THREAD

**Issue by nadavkav** [dbnschools/moodle-theme_fordson#12]
Several minor code fixes for solving "Notice: Undefined property: stdClass:: ..." can be PR #10 
Please review and see if you can integrate.

**Comment by nadavkav** [comment]
Ping @hannaedelman

**Comment by dbnschools** [comment]
OK.  I'll take a look and merge this.  I may just do it manually because I am pretty sure I have updated github since this was introduced.  This will be in the 1.6.5 release.  Although in my testing as long as the theme admin page had been saved then it doesn't give an error.

**Comment by nadavkav** [comment]
Bless you :smile: 
I think we are experiencing it because we use php7, and it might be a little bit more strict than earlier versions.

**Comment by nadavkav** [comment]
We also get a lot of those messages on the frontpage layout, only when debug mode is set for DEVELOPER.

**Comment by dbnschools** [comment]
Fixed.   https://github.com/dbnschools/moodle-theme_fordson/commit/c09dad724268809a2daa6415e09e1223cdbee430

**Comment by dbnschools** [comment]
I fixed each of the layout files.  I saw it wasn't limited to the 2columns file.

**Comment by dbnschools** [comment]
New versions are now published on Moodle.org.

**Comment by nadavkav** [comment]
Bless you!
(btw, amazing theme!)
