### ISSUE TITLE
Sorting according to courses progress

### ISSUE THREAD

**Issue by CappiLucky** [dbnschools/moodle-theme_fordson#121]
Hello, 
Thank you for this wonderful theme !

I wanted to share an idea with you : create a option able to sort according courses progress. This option (in course overview) can simplify the way to view courses : what student have to finish first for exemple. 
I don't think there is a plugin for that. So maybe it be useful for many of us to implement that in your theme ? 

Have a good week, 
Manon

**Comment by dbnschools** [comment]
Thank you for the suggestion.  We will keep this in mind.
