### ISSUE TITLE
Notice: Undefined property: stdClass::$enhancedmydashboard in /theme/fordson/config.php on line 154

### ISSUE THREAD

**Issue by leac** [dbnschools/moodle-theme_fordson#122]
I'm running Moodle 3.9 and I get that error, and some others, on some admin screens.  

The other errors are:

```
Notice: Undefined property: stdClass::$blockdisplay in /theme/fordson/config.php on line 162
Notice: Undefined property: stdClass::$blockdisplay in /theme/fordson/config.php on line 175
Notice: Undefined property: stdClass::$blockdisplay in /theme/fordson/config.php on line 199
Notice: Undefined property: stdClass::$blockdisplay in /theme/fordson/config.php on line 205
```

I think adding an `isset()` check could solve the issue.

**Comment by dbnschools** [comment]
Please go to Fordson Theme Admin Page and Save Settings.  This can happen when the theme is upgraded but you don't save settings for new features.  Simply saving theme settings will register a value for the variable and fix the issue.
