### ISSUE TITLE
theme_boost/tooltip.js

### ISSUE THREAD

**Issue by anrichp** [dbnschools/moodle-theme_fordson#123]
Moodle Version: 3.9.2

![Screenshot 2020-10-06 160236](https://user-images.githubusercontent.com/6475395/95219631-82eac680-07ed-11eb-8add-d7565572d6e0.jpg)

We have recently upgraded our sandbox Moodle site to 3.9.2 and updated Fordson to the latest release.

We have noticed in the browser console that the theme_boost tooltip library does not load and throws a 404 error.

This has caused some focus issues when loading page elements using Rangy.

**Comment by Kordopatis** [comment]
Any news?

**Comment by dbnschools** [comment]
What version of Fordson did you use and what is your setup?  I've not encountered this error before.

**Comment by emostoyanov** [comment]
I have the same error with vanilla Moodle 3.10 and Fordson. Apparently there is something changed with the Boost theme in this version of Moodle since the same error appears for other Moodle modules.

**Comment by mnods** [comment]
Hi, i'm getting this too in 3.9.3+ (Build: 20210108)

require.min.js:5 Uncaught Error: No define call for theme_boost/tooltip
http://requirejs.org/docs/errors.html#nodefine
    at makeError (require.min.js:5)
    at Object.completeLoad (require.min.js:5)
    at HTMLScriptElement.onScriptLoad (require.min.js:5)

**Comment by mnods** [comment]
Hi, i'm not 100% this is everything but i think the boostrap updates

https://github.com/moodle/moodle/commit/6a4ce7b0a357e2a3bdd646ac3ff97e3bb69cbacd#diff-7cddb69ffb728c627ed8f03d868c29a9c88ce7fa89329233e6618486032deffb

require the call to tooltip to be changed from

**theme_boost/tooltip**

**theme_boost/bootstrap/tooltip**
 
https://github.com/dbnschools/moodle-theme_fordson/blob/cafb5178b4d855d1ca2a90d3250c7009d6869922/templates/mydashboard.mustache#L124

https://github.com/dbnschools/moodle-theme_fordson/blob/cafb5178b4d855d1ca2a90d3250c7009d6869922/templates/columns2.mustache#L128

https://github.com/dbnschools/moodle-theme_fordson/blob/cafb5178b4d855d1ca2a90d3250c7009d6869922/templates/frontpage.mustache#L154

**Comment by interfaceslivres** [comment]
any information on how to solve this issue ?

**Comment by dbnschools** [comment]
Fixed in M310 Release 2.1
