### ISSUE TITLE
CSS not working in Moodle 10

### ISSUE THREAD

**Issue by cprudhoe** [dbnschools/moodle-theme_fordson#124]
I updated to Moodle 10 and found the the Fordson SCSS codes are not working in Moodle 10.

Thank you for providing the Fordson Theme. I set the colors in the custom colors utility but my site comes up with a white background.  Please see https://www.musapp.com/music  with username = betatester and password = BetaTester.
I trust you can fix the CSS codes soon.

Thanks again,
Clarence Prudhoe
musapp.club
cprudhoe@musapp.com

**Comment by cprudhoe** [comment]
I updated to Fordson version 10 and to my dismay, the Raw initial SCSS and Raw SCSS added commands are not working.

I installed Fordson v10 in Moodle 10 and opened the admin panel.  I selected appearance/Fordson/Colours.  I have the branding colours selected and only some of them are being applied.  The background colour is not being used.  My site looks like the standard Boost theme. 

Please see this at www.musapp.club.

Thanks for the use of the Fordson theme.  I hope you can fix this issue soon.
Clarence Prudhoe

**Comment by rebelsoxuk** [comment]
Hi.
We are having the same issues with the site defaulting to a standard Boost theme after the recent update (to Moodle 3.10.1+ Build: 20210122), regardless of which preset we use. :(
All the site is now just a white background

Regards

**Comment by dbnschools** [comment]
Fixed with Release 2.1 for Moodle 3.10
