### ISSUE TITLE
Moodle 3.9.3+ Breaks Dropdown Menu Items Font/Background Color

### ISSUE THREAD

**Issue by martygilbert** [dbnschools/moodle-theme_fordson#126]
I'm using Fordson 2020061800.

I just upgraded from Moodle 3.9.2+ (20200924) to Moodle 3.9.3+ (20201211) and it has broken the way the dropdown menu items are displayed.

It seems the background color is still the same, but the menu font is now white and the top menu item is selected **in addition to** whichever item is hovered over by the cursor.

## Before
In 3.9.2+, the highlighting on the menu item looks like this:
![Screenshot from 2020-12-11 15-47-19](https://user-images.githubusercontent.com/616253/101953482-6d689300-3bc8-11eb-8b16-f6e2bb476466.png)

## After
After upgrading to 3.9.3+, it now looks like this:
![Screenshot from 2020-12-11 15-35-42](https://user-images.githubusercontent.com/616253/101953503-76596480-3bc8-11eb-97d1-0aed6f478b7d.png)

I'm not great with HTML/CSS, but I thought I would post it hear in case it was an easy fix to push out. I can provide more info if necessary.

**Comment by dbnschools** [comment]
Drop this into the top SCSS text box on the Fordson Color page.  This has also been answered in the Moodle.org theme forum  

https://moodle.org/mod/forum/discuss.php?d=414812



// Dropdowns
$dropdown-bg: $white !default;
$dropdown-border-color: rgba($black, 0.15) !default;
$dropdown-divider-bg: $gray-200 !default;
$dropdown-box-shadow: 0 0.5rem 1rem rgba($black, 0.175) !default;

$dropdown-link-color: $gray-900 !default;
$dropdown-link-hover-color: darken($gray-900, 5%) !default;
$dropdown-link-hover-bg: $gray-200 !default;

$dropdown-link-active-color: $white !default;
$dropdown-link-active-bg: $gray-400 !default;

**Comment by martygilbert** [comment]
Shoot. I checked the tracker and GitHub, but not the forums. Sorry to cause
extra work, and thanks for the quick response!

--
Marty Gilbert
martygilbert@gmail.com

**Comment by martygilbert** [comment]
Just to circle back around on this one -

Copying/pasting those values didn't help. I'm using the Modern Moodle preset, and I believe those values were unchanged. Pasting your suggested values in the SCSS box (top one under Colors) caused my entire theme to freak out :) Yikes! Freak out may be harsh. It made it look plan and very Boost-esque.

I adjusted `$dropdown-link-active-color` in the `Modern Moodle.scss` file, and it actually adjusted the value - yay! I'll play with those more to get them where I want them.

But I'm still getting multiple menu items highlighted when I click the menu - typically the top menu item and the one my mouse is on are both highlighted:
![Screenshot 2020-12-14 133911](https://user-images.githubusercontent.com/616253/102121318-cbd48200-3e11-11eb-8060-ac94311e7a08.jpg)

Like I said earlier, everything was working fine in Moodle 3.9.2+, but a simple upgrade to Moodle 3.9.3+ broke things.

NOTE: I know you closed this issue. If you'd prefer I take this up on the Moodle forum, I'm more than happy to do so.

**Comment by dbnschools** [comment]
Make sure you have updated Fordson as well as Moodle.  Usually we fix CSS issues along the way with the Moodle versions, so if you have the old Fordson then you must update that too.

Many people update Moodle but forget about the plugins that also need to be updated.

**Comment by martygilbert** [comment]
Thanks for the tip, Chris.

I'm using the version (2020061800), listed as supported for Moodle 3.9 on the Moodle plugins page. I see you don't have a branch for `moodle39` yet, so I've tested it by a) downloading the zip from Moodle and b) checking it out from the commit hash cafb517, both with the same result. Am I using the correct version?

I did a little more digging to find out where Moodle broke this functionality. It appears it worked fine with weekly release version 20201028 (beff06), but upgrading to the next weekly 20201030 (3b0d95) broke it, and it's still broken in the most recent weekly release (3.9.3+ 20201211 6334f). 

I have 3 dev sites setup to illustrate this. One running 20201028, one running 20201030, and one running the most recent release. The first one works, while the final two do not. I'm more than happy to give you a URL and temporary credentials offline if you'd like to see it.

We've been using Fordson for...2+ years now? Emma Richardson told me about it at MtMoot one year, and we've been using it ever since. I appreciate all of the hard work that you've put into making it an excellent theme.

### Resources
In case any of these might help:
* [Here are the diffs](https://github.com/moodle/moodle/compare/beff061...3b0d95)  on GitHub between Oct 28 (working) and Oct 30 (broken)
* [Here is the full diff](https://pastebin.com/2WNj917f) sames dates as text on pastebin. 2148 lines.
* [Here is the diff](https://pastebin.com/g8qY0G8r) same dates, only with files that contain the string 'dropdown'. 520 lines. Didn't know if that would help.
