### ISSUE TITLE
Warning in course renderer.

### ISSUE THREAD

**Issue by barteno** [dbnschools/moodle-theme_fordson#127]
Hi,
We've encountered a minor issue (actually a warning) in m.39 version

```
PHP Notice:  Undefined variable: catcontent in 
 /fordson/classes/output/core/course_renderer.php on line 249
```
All the best,
Bart

**Comment by dbnschools** [comment]
Please go to Fordson Theme Admin Page and Save Settings.  This can happen when the theme is upgraded but you don't save settings for new features.  Simply saving theme settings will register a value for the variable and fix the issue.
