### ISSUE TITLE
Activity icons in course competencies page are huge

### ISSUE THREAD

**Issue by turtaniumx** [dbnschools/moodle-theme_fordson#13]
The icons for activities linked by a competency are too big in the course competencies page

**Comment by dbnschools** [comment]
We don't use competencies.  Can you share more details so I can take a look.  Maybe a screenshot and details of what page within competencies where the icons are too big.

**Comment by dbnschools** [comment]
[data-region="coursecompetencyactivities"] .list-inline-item img {
    width: 32px;
}

Try adding this to the custom SCSS box at the bottom of Fordson's colors page.  
If that fixes it then I will include this in the next release of Fordson.

**Comment by turtaniumx** [comment]
Thank you. That code snippet seems to fix the problem.
