### ISSUE TITLE
Please replace 'PD' string with 'Personal Development' string

### ISSUE THREAD

**Issue by germanvaleroelizondo** [dbnschools/moodle-theme_fordson#14]
Hi,
I like the Fordson theme. 
I have just translated the latest version into Mexican Spanish. 
I had great difficulty translating 'PD' which appears several times in the English language strings in AMOS.

If PD does indeed mean 'Personal Development' as I guessed, could you please replace 'PD'  with 'Personal Development' in the English language strings for this plugin?.

This would make it easier for all the other Moodle translators and will have less chance of errors in the translation process into other languages, as your plugin is extremely popular in many countries.

Thanks in advance for your help.

**Comment by dbnschools** [comment]
Sorry that it didn't translate well.  Let's see what we can do to fix it.

When we use PD in K-12 education it stands for **Professional Development**.  Almost all our teachers use the simple PD in place of saying "professional development".

I am assuming you mean these strings:  
$string['mypd'] = 'My PD';
$string['homemypd'] = 'PD Home';
$string['thismypd'] = 'This PD';

As you can see Professional Development is a bit long for text in a menu heading.  Would you suggest I just remove it?

**Comment by germanvaleroelizondo** [comment]
Hi, Maybe you could use:

$string['myprofessionaldevelopment'] = 'My PD';
$string['homemyprofessionaldevelopment'] = 'PD Home';
$string['thismyprofessionaldevelopment'] = 'This PD';

And, of course, update all references for these strings.
This way, all Moodle AMOS translators would immediately know the meaning of the abbreviation :)

**Comment by dbnschools** [comment]
I just updated the language string on github and will soon publish this update on Moodle.org.   Hopefully this works better for translators.  What do you think?

https://github.com/dbnschools/moodle-theme_fordson/commit/cb19e919c2b544a705704fefc9b41fe71d4a31df

**Comment by germanvaleroelizondo** [comment]
I think it will help translators unfamiliar with the PD abbreviation usage in K-1 (as myself, a lecturer in veterinary pathology) :)
Thanks.
