### ISSUE TITLE
Difficulty with plugin "collapsed topics"

### ISSUE THREAD

**Issue by kdidier51** [dbnschools/moodle-theme_fordson#15]
Hello,
In my courses, I use the plugin "collapsed topics". 
![fordson3](https://user-images.githubusercontent.com/29543774/37240242-3648bc7c-2449-11e8-975b-db3ecedd1eda.JPG)
With the new version of Fordson, I have an error at screen 
![fordson](https://user-images.githubusercontent.com/29543774/37240233-1f2325f0-2449-11e8-816f-ec60b6963e60.JPG)
If I change "Format de cours", this message does not appear any more. 
Your theme is very excellent, but my English is very poor !!!
Thanks for your answer
Best regards
Didier CABY - Reims France

**Comment by dbnschools** [comment]
I'm not quite sure why but if you turn off "This Course" menu and it will go away.  Gareth might have some insight into why collapsed topics causes this issue and maybe he might have a solution that I could change my code to be more compatible

![moodle 3 4 administration appearance themes fordson](https://user-images.githubusercontent.com/28066305/37283187-732b7370-25cd-11e8-941c-afcf00acf338.png)

**Comment by kdidier51** [comment]
It's Ok, without "Display this course menu", the messages disappear. 
Now, when I go to Site Administration/Appearance/Fordson, I have this message : 
![fordson](https://user-images.githubusercontent.com/29543774/37327687-99f2752e-2697-11e8-847f-be55fc7a34ac.JPG)
There are about 100 lines. 
I have tried with Edge and Chrome. 
Thanks for your help
Kinds regards
Didier CABY

**Comment by dbnschools** [comment]
I am not sure sure what is going on with your install but I also use record rtc on a production site and we do not get these errors.  Are you sure you setup everything correctly?  Something is not right.  How are you installing stuff?

**Comment by kdidier51** [comment]
Bonjour,
I have desinstalled the plugin record rtc, and all is good. I am not sure that somebody used it. 
Thanks for your answer.
