### ISSUE TITLE
Difficulty with Course Dashboard Button Assignments option

### ISSUE THREAD

**Issue by k-holland** [dbnschools/moodle-theme_fordson#16]
Hi there, love your theme! I've installed it on a 3.4.2+ site, and uploaded the "Basic Moodle and Mountaineering" course from https://moodle.net/?courseid=967.
When I try to view the Assignments option from the top nav course dashboard button, it doesn't show the correct assignment list and gives the following error: 
**Assignments
Found more than one record in fetch() !**
All the other Activities shortcuts are working fine.

Many thanks in advance, karen

**Comment by dbnschools** [comment]
I am assuming you mean the links that show you all the assigments in a course or all the books, etc, grouped together on one page?  I think something on your site went wrong when you performed the import of the course.  It works just fine on my site.  Try re-importing the course.
