### ISSUE TITLE
Category display as icons run vertically instead of horizontally

### ISSUE THREAD

**Issue by bollycanuk** [dbnschools/moodle-theme_fordson#18]
Running Moodle 3.5 (Build: 20180517) with Moodle 3.5 Fordson v3.5 release 1 (2018051700)

If I set Category display icons to Yes in Preset Adjustments, category icons are displayed on Front page but are listed vertically instead of horizontally. In previous versions they were listed horizonatlly for screen width then wrapped to the next line(s).

![fordon 3 5 category icons verticl](https://user-images.githubusercontent.com/9040146/40202179-2861a598-59ef-11e8-8f85-d2bca672544d.JPG)

**Comment by kennibc** [comment]
Good find.  I'll check it out next week and get a fix.
