### ISSUE TITLE
Theme header background image  is missing after turning off theme designer mode. 

### ISSUE THREAD

**Issue by NcuIT** [dbnschools/moodle-theme_fordson#2]
I added my own photo and had theme designer mode on and when i turn off theme designer mode the image disappears. i have purged the cache and behavior doesn't change, checked a different machine even.  

![moodle snip1 theme designermodeoff](https://cloud.githubusercontent.com/assets/28809870/26253929/90644d96-3c7a-11e7-801d-96b4e54a9f24.PNG)
![moodle snip2 theme designermodeon](https://cloud.githubusercontent.com/assets/28809870/26253933/91ca5298-3c7a-11e7-9bd3-fdee996b9050.PNG)

**Comment by dbnschools** [comment]
What version of Moodle and Fordson are you using?

**Comment by NcuIT** [comment]
Moodle 3.2.3.

Fordson 1.4.6.


I just built this moodle a few weeks ago.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dbnschools** [comment]
Is it possible there is a permission issue on the cache and it is not deleting properly?  Delete the actual cache folder and see how it regenerates.

**Comment by NcuIT** [comment]
currently i have it set to 770 permissions for development,  where is the cache folder located?  i found the main one under /var/www/cache but that other things that killed the server when i renamed it?






On May 21, 2017, at 2:34 PM, Dearborn Public Schools <notifications@github.com<mailto:notifications@github.com>> wrote:


Is it possible there is a permission issue on the cache and it is not deleting properly? Delete the actual cache folder and see how it regenerates.

**Comment by dbnschools** [comment]
Moodle cache is stored in the Moodle data directory setup when you
installed Moodle.  If this is a test server and you run multiple instances
of Moodle you must make sure each instance has a unique data directory.
Otherwise the defaults will all want to use the same folder and it can
cause weird issues like this.

**Comment by NcuIT** [comment]
Didn’t work,  I deleted all the files out of the cache directory mentioned, im only running one moodle on this server as we are about to move it to production later this summer.


The image shows up in the course tiles, but not the header still.

**Comment by dbnschools** [comment]
Do you have a URL I can take a look at?  I need to see the html.

Chris Kenniburg
Webmaster, Dearborn Public Schools
313-827-3084
Michigan Moodle <http://michiganmoodle.dearbornschools.org/>
Technology <http://technology.dearbornschools.org/>
Tech Coaches <http://techcoaches.dearbornschools.org/>

**Comment by NcuIT** [comment]
https://Moodle1718.northcentral.edu


I just put it on the internet.

**Comment by dbnschools** [comment]
Can you please use a jpg image just to rule out that as an issue?

Chris Kenniburg
Webmaster, Dearborn Public Schools
313-827-3084
Michigan Moodle <http://michiganmoodle.dearbornschools.org/>
Technology <http://technology.dearbornschools.org/>
Tech Coaches <http://techcoaches.dearbornschools.org/>

**Comment by NcuIT** [comment]
I have changed it to a jpg, purged the cache from gui and deleted it in moodle_data just to be sure and still didn’t work.

**Comment by dbnschools** [comment]
Here is where the defaultheaderimage is attached to a class.  
https://github.com/dbnschools/moodle-theme_fordson/blob/master/lib/scss_lib.php#L159-L166

It attaches to .headerbkg

Also, please update to the latest version 1.4.8.

**Comment by NcuIT** [comment]
Thanks. To be honest I’m not sure what I’m supposed to do with that link, Im not a php developer.




The last version is only for 3.3, my other plugins haven’t made the move yet.

**Comment by NcuIT** [comment]
I have checked the code section and they match.

**Comment by dbnschools** [comment]
Have you made any other customizations?  It seems to be an issue where that code from the link I provided is not being applied when your site is compiling the css.  It does in designer mode because the CSS is rendered and displayed without cache.  For some reason when your site renders the css and cache's it there is an issue.  At least that is all I can assume with no other access.

**Comment by NcuIT** [comment]
i have Php-Opcache turned on and Moodle caching on.

thanks for help! ill try a turning them all off and add them back one by one.


thanks again.


On May 24, 2017, at 9:55 AM, Dearborn Public Schools <notifications@github.com<mailto:notifications@github.com>> wrote:


Have you made any other customizations? It seems to be an issue where that code from the link I provided is not being applied when your site is compiling the css. It does in designer mode because the CSS is rendered and displayed without cache. For some reason when your site renders the css and cache's it there is an issue. At least that is all I can assume with no other access.

**Comment by dbnschools** [comment]
Thanks for bringing this up.  I am working on a new version which will not utilize prescss (current method) to attach an image to the headerbkg class.  The new way will also make pages load faster because you are not loading the default image and then the course image ontop of it.  I built in logic to determine what image to display and only display one image.  This will be in the 1.4.9 version of Fordson.  It is now pushed here to github if you wanted to try it out.

**Comment by NcuIT** [comment]
Thanks!  Will the new version require moodle 3.3 or will it support 3.2.3?




Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by dbnschools** [comment]
It is only for Moodle 3.3.

We are focused on Moodle 3.3 for all new improvements and features.

Chris Kenniburg
Webmaster, Dearborn Public Schools
313-827-3084
Michigan Moodle <http://michiganmoodle.dearbornschools.org/>
Technology <http://technology.dearbornschools.org/>
Tech Coaches <http://techcoaches.dearbornschools.org/>

**Comment by NcuIT** [comment]
Ok so I upgraded to 3.3+ just now,  and fordson 1.4.8  issue is still happening.  Any ideas?

**Comment by dbnschools** [comment]
The version 1.4.9 which I am about to publish on github might solve your issue.  I reworked how the header image is displayed.

**Comment by dbnschools** [comment]
Did the issue go away with version 1.4.9 or 1.5.0?

**Comment by NcuIT** [comment]
hey sorry, i had some things blow up and couldn’t work on it,  i have upgraded to 1.5.0 the header files now work, none of the icons are working,  like they are all gone now?  [cid:F348D44A-AB81-409B-9509-3155E4195B51@northcentral.edu] [cid:F6219EA5-DDA7-4155-9A82-462A4B853540@northcentral.edu]
On May 31, 2017, at 12:41 PM, Dearborn Public Schools <notifications@github.com<mailto:notifications@github.com>> wrote:


Did the issue go away with version 1.4.9 or 1.5.0?

**Comment by dbnschools** [comment]
I believe you have a server issue going on.  It could be cache or something else.  It doesn't seem to load things properly for you.

**Comment by NcuIT** [comment]
it seems to only be on the fordson theme and the icons come back after i turn on theme designer mode,  i have cleared the caches and still missing.



On Jun 5, 2017, at 1:13 PM, Dearborn Public Schools <notifications@github.com<mailto:notifications@github.com>> wrote:


I believe you have a server issue going on. It could be cache or something else. It doesn't seem to load things properly for you.

**Comment by NcuIT** [comment]
I have also switched back to stock boost theme and the icons came back,  I went in and deleted fordson from the db and the theme files and loaded a fresh copy and still the same behavior.   i have only enabled Opcache on php7.0  the icons worked on 1.4.6 tho.


thanks for your help on narrowing this down!

On Jun 5, 2017, at 2:13 PM, Cody L. Frank <clfrank@northcentral.edu<mailto:clfrank@northcentral.edu>> wrote:

it seems to only be on the fordson theme and the icons come back after i turn on theme designer mode,  i have cleared the caches and still missing.



On Jun 5, 2017, at 1:13 PM, Dearborn Public Schools <notifications@github.com<mailto:notifications@github.com>> wrote:


I believe you have a server issue going on. It could be cache or something else. It doesn't seem to load things properly for you.

**Comment by dbnschools** [comment]
You might be having issues due to php or server limits where rebuilding the cache is not completed and your server gives up, thus not getting all the styles and images.  Check out the major bug being reported here for Moodle 3.2 and 3.3 Boost Based themes...  https://tracker.moodle.org/browse/MDL-58646
