### ISSUE TITLE
Icon navigation boxes don't auto-fit to label width

### ISSUE THREAD

**Issue by bollycanuk** [dbnschools/moodle-theme_fordson#20]
Fordons v3.5 r5-30:
Noticed that if label on the icon navigtion bar are long, the text simply extends beyond the box width instead of the box auto adjusting to the text width. See below
![fordson 3 5 icon nav label width issue](https://user-images.githubusercontent.com/9040146/40744900-faa4ef72-6423-11e8-8b30-bd68e09027fc.JPG)

Adding the following to the Raw SCSS section fixed it. 
.iconset .btn.btn-secondary {
  width: inherit;
}

**Comment by dbnschools** [comment]
New version Release 3 for Moodle 3.5 will fix this.  It uses the width setting as the min-width and therefore can expand to accomodate more text if needed.
