### ISSUE TITLE
Fordson prevented upgrade from 3.4.3 to 3.5

### ISSUE THREAD

**Issue by andobrien** [dbnschools/moodle-theme_fordson#22]
When upgrading from Moodle 3.4.3 to 3.5 with the Fordson theme enabled, the upgrade fails returning a web server error that the page cannot be displayed.  I had checked for all plugins to be updated before performing the upgrade.

Changing the theme to Boost allowed the upgrade to go through.  As soon as the upgrade was done I was able to switch back to the Fordson theme.

Since upgrading to 3.5 I have noted that the Fordson theme has been upgraded - so this issue may have already been spotted and resolved.

**Comment by dbnschools** [comment]
https://bookshare.dearbornschools.org/fordsontheme/chapter/installation/

When upgrading between major versions of Moodle it is recommended to switch back to Boost and then upgrade everything including the Fordson theme after Moodle is updated.

**Comment by andobrien** [comment]
Sorry – my bad for missing that guidance.  Thanks for the quick response, but more importantly, thank you for the awesome work you’ve done and continue to do to make it easy for me to make our Moodle look good!

**Comment by dbnschools** [comment]
No problem.  Still working on the documentation.  It's a labor of love.  Thank you for your kind words.  I finally think the Fordson theme is reaching the vision we had for it way back in Moodle 3.2.  

Please consider giving Fordson a like on Moodle.org as that is all we ask if you like using the theme.
