### ISSUE TITLE
carousel problem

### ISSUE THREAD

**Issue by samuelcalegari** [dbnschools/moodle-theme_fordson#23]
hello
i have a problem on homepage carousel, there is no transition between slides
thanks  in advance ! 
versions : Moodle 3.5; Fordson v3.5 release 2 2018060100

**Comment by dbnschools** [comment]
There is no transition. I think it just advances.

**Comment by samuelcalegari** [comment]
this solve my problem 👍
https://github.com/moodle/moodle/compare/MOODLE_35_STABLE...grabs:MDL-61515-MOODLE_35_STABLE
