### ISSUE TITLE
Invalid parameter error

### ISSUE THREAD

**Issue by jellysmith** [dbnschools/moodle-theme_fordson#24]
<img width="456" alt="screen shot 2018-06-15 at 9 42 44 pm" src="https://user-images.githubusercontent.com/16172403/41495890-a7ad198c-70e6-11e8-8f06-ba5ad927e35b.png">

All courses imported from a Moodle 3.1 installation show this "invalid parameter" error on the main page of the class. This error does not appear with newly created 3.5 classes, or when only the default Boost theme is used.

**Comment by kennibc** [comment]
I found an issue that might cause a problem.  It deals with blocks.  I'll be uploading a new version before the end of the week.

**Comment by jellysmith** [comment]
Thanks for the new version! I no longer get this error.
