### ISSUE TITLE
Font Awesome icon list URL

### ISSUE THREAD

**Issue by izendegi** [dbnschools/moodle-theme_fordson#25]
The help text of the icon fields (such as createicon, slideicon and others) has a link to [this Font Awesome list](http://fortawesome.github.io/Font-Awesome/cheatsheet/), but Moodle actually uses the 4.7.0 version so the link should be this one:

https://fontawesome.com/v4.7.0/icons/

I've wasted some time trying to know why some icons were not working until I realized this, so this change may save time to others.

I've searched in AMOS and these are the strings that should be changed: _marketingicondesc_, _navicondesc_ and _naviconslidedesc_

**Comment by dbnschools** [comment]
Thanks!  This was most likely carryover from the previous theme.  I updated the theme for next release.
