### ISSUE TITLE
Block Course View

### ISSUE THREAD

**Issue by cljkoopman** [dbnschools/moodle-theme_fordson#27]
The Fordson theme has the option to open the course blocks with a button "Course blocks" at the top of the course page. Great! I like that!

Is it possible to repeat this button at the bottom of the block overview after opening it? That saves a lot of scroll work.

Kind regards,
Kees Koopman.

**Comment by dbnschools** [comment]
I see, so you can close it quickly after opening the listing of blocks?

**Comment by cljkoopman** [comment]
Thank you for your comment.
I use a number of blocks on a course page (calender / progress / html / level / stash / etc.).
When I open the block with "Course blocks", I sometimes have to scroll tightly to get to the bottom of my blocks. Now I have to scroll back again to push "Course blocks".
That is why it seems handy to have the opportunity to close it again ("Course blocks") at the bottom of that block.

**Comment by cljkoopman** [comment]
Thanks!
Is it difficult to set the button at the top **and** at the bottom of a page?
Your custom css works perfect!

**Comment by dbnschools** [comment]
Yes.  It is difficult because the javascript targets a div ID and you cannot have 2 with the same name.  So I think we will keep the button at the top as a workaround and usability improvement until I can circle back around to see about maybe a better solution.

**Comment by cljkoopman** [comment]
Great. Thanks!
