### ISSUE TITLE
[Improvement proposal] Open icon navigation links on a new tab/window

### ISSUE THREAD

**Issue by izendegi** [dbnschools/moodle-theme_fordson#28]
Now all the links of the icon navigation bar are opened on the same window, it would be great if that can be setted up to be opened on a new tab/window.

**Comment by dbnschools** [comment]
What links exactly are we talking about?

**Comment by izendegi** [comment]
I mean those links of the Icon Navigation bar (nav1buttonurl, nav2buttonurl and so on); usually are links to other sites, and on those cases would be great to have an option to open them on a new tab/window.

**Comment by dbnschools** [comment]
Possibly in the future I can add that in as a variable.  I'd have to see.
