### ISSUE TITLE
breadcrumb li issue

### ISSUE THREAD

**Issue by ceremy1** [dbnschools/moodle-theme_fordson#29]
my moodle version  3.5+ so,
i have breadcrumb issue when i updated  to fordson theme version 2018062600 
like this
![brend](https://user-images.githubusercontent.com/13921682/42245849-0247a2be-7f23-11e8-83c8-2b24d1d776f0.png)

breadcrumb covered with white color
how can i fix it
best regards

**Comment by dbnschools** [comment]
Remove #fff(white) from the Fordson colors page for Breadcrumb background. That should fix it.
