### ISSUE TITLE
Make the whole course image clickable (same for markettiles)

### ISSUE THREAD

**Issue by fxpar** [dbnschools/moodle-theme_fordson#3]
Hi, 

Thanks for this great theme.
Trying to find a way to have the whole courses box and markettiles clickable. 

For now, the button is very small and inside a pile of divs. It seems users tend to click directly on the image with there finger... not looking for which part of the tile is clickable.

Is there a way to access the parts of the {{{button}}} to create a link around the divs?

 ```html
       <div class="col-md-4">
        <div class="market-tile"> 
            <h3 class="card-title">{{{title}}}</h3>
            <div class="marketcontent {{{tileimage}}}">
            <p>{{{content}}}<p>
            </div>
            {{{button}}}  
        </div>
        </div>
```

Thank your for your help
Regards 

François

**Comment by dbnschools** [comment]
After review we do not want to make the whole market tile a link because we use it to display text list with links.

**Comment by fxpar** [comment]
Hi, 

Thank you for taking time to answer and considering the proposition.
Regards
François

**Comment by fxpar** [comment]
Hi again, 

Just some example of clickable course tile... 

Open learn
![image](https://user-images.githubusercontent.com/11584406/28329423-12d4440e-6bea-11e7-8ccf-9286cd5f440d.png)

Udacity
![image](https://user-images.githubusercontent.com/11584406/28329454-2dfef378-6bea-11e7-91de-b40271e3ae3c.png)

In fact, except on moodle, I can't find examples of big tiles where only a tiny spot is clickable.
Hope your team has a change of mind.

Best regards
François

**Comment by dbnschools** [comment]
You are very persuasive.  I will take another look and see what we can do.  However, part of how we use the marketing blocks is to include lists of links in the text area.  If it was all one link then this would break.  I don't know we want to loose that ability.

**Comment by fxpar** [comment]
Hi,
It makes perfectly sense for market tiles if multiple links are to be included. I do agree with you on that. No problem. 

Thanks for checking for the course tiles. That would be awesome!

Best regards
François

**Comment by dbnschools** [comment]
The course tiles we can fix.  I'll take a look Friday

**Comment by dbnschools** [comment]
Francois,
While I do not want to make the whole Marketing Tiles clickable, I did see value in making the frotnpage course tiles clickable.  In the next release I plan to offer 3 different styles for course tile display.  This will change the way the courses display on the homepage as well as in the categories.  Part of that is a fix to make the whole tile clickable.  The current frontpage tiles will be known as Style 3 moving forward and when selected it will also be used in course categories.  

This will create consistency from the frontpage and course category browsing.  It will also allow you to select from three different styles!

**Comment by fxpar** [comment]
Hi, 

This is awesome. You really rock!
Thank you very much for your work. I am impatient to test this new UX.
3 different style... that's a lot more than I asked ;)
Thanks again
Cheers
François

**Comment by dbnschools** [comment]
V 155 should fix this for you.  It's on moodle.org now too.

**Comment by fxpar** [comment]
Hi, 
Style 3 works like a charm, and the animation is great!
Thank you for this customization.
Best regards
François
