### ISSUE TITLE
Undefined property: stdClass::$showcustomlogin

### ISSUE THREAD

**Issue by gjb2048** [dbnschools/moodle-theme_fordson#30]
Hi Chris,

When working with Fordson on M3.5 version:

$plugin->version   = 2018062600;
$plugin->release  = 'Moodle 3.5 Fordson v3.5 release 3 update 3';

I noticed:

PHP Notice:  Undefined property: stdClass::$showcustomlogin in F:\moodledev\moodle35\theme\fordson\lib\scss_lib.php on line 208

in my php.log file.  Can't remember how to replicate but was probably after switching to the theme on a course using the url ('allowthemechangeonurl' core setting set).

Gareth

**Comment by dbnschools** [comment]
Thanks.  I will try to reproduce the error.
