### ISSUE TITLE
Single quote in text causes bug

### ISSUE THREAD

**Issue by Edunao** [dbnschools/moodle-theme_fordson#31]
Hi Chris,

We have an issue while using Marketing Tiles with theme fordson. 
Adding a marketing tiles with a text containing single quotes in a link causes the plugin to bug.

![image 3](https://user-images.githubusercontent.com/22300677/43150221-a6928cac-8f69-11e8-9220-0f7e2c3abde6.png)
![image 2](https://user-images.githubusercontent.com/22300677/43150226-a9243c72-8f69-11e8-9754-350aa477b382.png)

Best regards
Edunao's team

**Comment by dbnschools** [comment]
Can you post exactly what you tried to enter for the button area.  I think you are trying to make the link open in a new window and it will not work.  Remove the code and just put an actual link like http://dearbornschools.org

**Comment by Edunao** [comment]
I was not trying to open the link in a new window. I was just trying to write "C'est parti !"

![capture d ecran 2018-07-30 a 16 50 52](https://user-images.githubusercontent.com/22300677/43404855-c7837e68-9418-11e8-83b3-d52d242cea4a.png)

**Comment by dbnschools** [comment]
OK.  I'll take a look.

**Comment by dbnschools** [comment]
OK.  I found the issue.  I was using format_text in the core_renderer.php file.  If I switch this to format_string for the button text it fixes the issue.  This will be a fix in the next release of Fordson.

**Comment by Edunao** [comment]
Hi,
We have just tested the latest version for Moodle 3.3 and the issue is still present.
Could you please tell me which line i need to change to resolve the problem.
Many thanks in advance.

**Comment by dbnschools** [comment]
We are developing and working on Moodle 3.5.  We aren't fixing the older versions as we only work on the versions we use.  

This function was changed:  https://github.com/dbnschools/moodle-theme_fordson/blob/master/classes/output/core_renderer.php#L548-L746

And this one:  https://github.com/dbnschools/moodle-theme_fordson/blob/master/classes/output/core_renderer.php#L799-L888

To include format_string when processing the text.  You might be able to just copy/paste those two functions into your core_renderer.php file.

**Comment by Edunao** [comment]
Understood, Many thanks
