### ISSUE TITLE
Navbar-dark option?

### ISSUE THREAD

**Issue by Robynstar** [dbnschools/moodle-theme_fordson#32]
We have a dark blue navbar, so all the black icons etc are very hard to see!
I see in the css there are options for navbar-dark, but we are stuck with navbar-light and I cannot find anywhere to change this

Looking in templates/navbar.mustache it seems that the navbar-light class is hard-coded?

**Comment by dbnschools** [comment]
It is like that in Boost too.  It is hard coded but you can easily change it to what you want.  I'll take a look and see if I can make a toggle between light and dark, or maybe just remove that and make a color chooser.

**Comment by dbnschools** [comment]
These are the Bootstrap variables that you can instantly change on the Fordson Colours page in the custom SCSS boxes.  Once you set this you wouldn't have to change the hard code.  
Something like this would go directly into the top SCSS box on the fordson colors page:

$navbar-light-color:                #fff;
$navbar-light-hover-color:          #ccc;
$navbar-light-active-color:         #fff;
$navbar-light-disabled-color:       #e3e3e3;

**Comment by Robynstar** [comment]
Cheers for that, had forgotten those existed!

Should I raise this on Boost instead?

**Comment by dbnschools** [comment]
You might want to but I suspect it isn't going to change.  They are producing a standard look and feel.  I might try to create a better solution but I haven't got the time right now.
