### ISSUE TITLE
Video plugin

### ISSUE THREAD

**Issue by ebugnet** [dbnschools/moodle-theme_fordson#35]
Hi,
I'm using Fordson with Spectrum Achromatic preset.
With this default setting, video JS player is not shown correctly: height too small.
I have to adjust my CCS with that:

.mod-indent-outer .mediaplugin {
    display: contents;
}

Don't know if it's a global fordson problem.

Éric

**Comment by dbnschools** [comment]
Thanks.  I've been looking into this.  Hopefully this will help fix the issue.

**Comment by dbnschools** [comment]
Should be fixed with the Update 9 release.
