### ISSUE TITLE
Strange "4" at class names

### ISSUE THREAD

**Issue by yorickreum** [dbnschools/moodle-theme_fordson#37]
Some of the class names suddenly end with a strange four, especially on the front page.

Example: _div.courses.frontpage-course-list-enrolled div.course-summary_ has changed to _div.courses.frontpage-course-list-enrolled div.course-summary4_

Is this a bug or a feature?

**Comment by dbnschools** [comment]
Yes.  It happens when you change the course tile options so that we can produce different styles etc.  This is a feature of Course Tile Display on the Fordson Theme Settings page.
