### ISSUE TITLE
Fix breadcrumbs in RTL mode

### ISSUE THREAD

**Issue by nadavkav** [dbnschools/moodle-theme_fordson#38]
When using styled breadcrumbs in RTL mode, the styles "pointers/arrows" between the hierarchy breaks.
Attaching LTR and RTL images to illustrate the issue:
RTL:
![image001](https://user-images.githubusercontent.com/231168/45373316-cb782b80-b5f7-11e8-92ce-6a5c3fceeaab.jpg)
And LTR:
![image002](https://user-images.githubusercontent.com/231168/45373322-d0d57600-b5f7-11e8-99f8-869909735571.jpg)

To fix it, I added the following code to the RAW SCSS inside the theme's Color management tab.
```
.dir-rtl ul.breadcrumb li:after{
  transform: scale(.707) rotate(315deg);
  -webkit-box-shadow:  -3px -3px 0 1px #fff, -2px -3px 0 2px #fff;
  box-shadow: -3px -3px 0 1px #fff, -2px -3px 0 2px #fff;
}
```
Please review this fix as see if you can add it to the (amazing!) theme you made, or maybe solve it more elegantly at the proper place inside the scss files.

Best,
Nadav

**Comment by dbnschools** [comment]
This should be completed in update 10 to Fordson.  Please test and confirm it works as desired.  I do not have a test environment for RTL.

**Comment by nadavkav** [comment]
Thank you, I will.
