### ISSUE TITLE
"Course Blocks" appears though deactivated

### ISSUE THREAD

**Issue by yorickreum** [dbnschools/moodle-theme_fordson#39]
Although theme_fordson|blockdisplay is set to "Single Column Boost Default" the "Course Blocks"-Button appears on the upper right-hand corner (only on the "This Course --> Participants"-page, everywhere else it's gone, as expected).
We guess, this ist a bug? Or is there another way to deactivate it here?

Kind regards!
Yorick

![image](https://user-images.githubusercontent.com/39629166/46082477-7a436c80-c19f-11e8-851e-fd8686f17d61.png)

![image](https://user-images.githubusercontent.com/39629166/46082364-33ee0d80-c19f-11e8-8751-47d8fd681683.png)

**Comment by dbnschools** [comment]
It becomes an issue if you switch back and forth between Boost and Fordson 3 column.
There are blocks that were added with Fordson 3 column setup and are set to appear in Column A,B,C and until those are deleted the system will think it needs to display them.  

I made a change in the template and I think it will correct this issue as far as just removing the button.
under /fordson/templates/blockspanelslider.mustache  add the {{#hasfpblockregion}} and {{/hasfpblockregion}} around the code for the button.  This will be included in the next release in Update 11.

```
{{#hasfpblockregion}}
<div class="text-right blockpanelbtn">
<button id="blocksliderbutton" class="btn btn-primary blockpanelbutton" type="button" data-toggle="collapse" data-target="#blockslider" aria-expanded="false" aria-controls="blockslider">
    <i class="fa fa-arrows-v" aria-hidden="true"> </i> <span class="blockbtntext">{{# str }} courseblockpanelbtn, theme_fordson {{/ str }}</span>
  </button>
</div>
{{/hasfpblockregion}}
```

**Comment by yorickreum** [comment]
Okay, I think this will solve the problem. Thanks a lot for your fast and helpful answer!

On occasion: Could you push update 10 to git? We're always updating from here…
