### ISSUE TITLE
Display bug

### ISSUE THREAD

**Issue by jrm-unamur** [dbnschools/moodle-theme_fordson#4]
Hi there,

When config param courseoverviewfileslimit is 0 (adminsettings/appearance/course), "Array" is displayed before <div id="learningcontent">
Function "headerimage()" in forsdon's core_renderer should return empty string instead of array() at line 109;
Regards

**Comment by dbnschools** [comment]
Fixed in next upcoming release 1.5.3
if (empty($CFG->courseoverviewfileslimit)) {
            if ($CFG->courseoverviewfileslimit == 0) {
                return '';
            }
            return array();
        }

**Comment by dbnschools** [comment]
if (empty($CFG->courseoverviewfileslimit)) {
            return '';
        }
