### ISSUE TITLE
Footer not staying at bottom of page - Moodle 3.6 alpha behaviour

### ISSUE THREAD

**Issue by bollycanuk** [dbnschools/moodle-theme_fordson#41]
I know the version 3.6 release is still a month away but I've been running Moodle 3.6 alpha for a while. The current Moodle 3.5 Fordson v3.5 release 3 update 12 (2018100100) theme works really well with it EXCEPT that the footer tends to scroll up with the page. What is really weird is that if I zoom my browser in or out, the footer position is always at the "bottom" of the portion of the page that is first visible - i.e. the home position. But the footer still scrolls up from that initial position when I scroll down the page.

Here is a page when I first load it:
![image](https://user-images.githubusercontent.com/9040146/46353166-87da7580-c629-11e8-89be-a4036f32aa13.png)

Here is the page when I scroll down. Footer follows the scrolling
![image](https://user-images.githubusercontent.com/9040146/46353284-c6703000-c629-11e8-923a-1c171f1a8a19.png)

Now if I zoom out to 80% the top portion looks like it should
![image](https://user-images.githubusercontent.com/9040146/46353396-118a4300-c62a-11e8-9407-7ed296dab798.png)

But scrolling down, the footer still scrolls up, albeit in a different vertical position.
![image](https://user-images.githubusercontent.com/9040146/46353485-472f2c00-c62a-11e8-832a-5dcb5c72bdf7.png)

cheers,
Derek

**Comment by bollycanuk** [comment]
It does NOT happen with the Moodle 3.6 Boost theme.

**Comment by dbnschools** [comment]
I've noticed it too on my dev site.  Once we get closer I will have to see what all they changed and try to fix it.  
Here's what I've got so far and it seems to help fix up some things:
```
#page-wrapper {height:auto;}
#region-main {
    border: 0;
    padding: 1.25rem;
    background-color: transparent;
}
```

**Comment by bollycanuk** [comment]
Yup, that seems to fix it.

many thanks!
Derek
