### ISSUE TITLE
Moodle 3.6 Build 20181031 issues with Fordson Moodle 3.6 initial release

### ISSUE THREAD

**Issue by bollycanuk** [dbnschools/moodle-theme_fordson#44]
### The initial relase version of Fordson was working with the Moodle 3.6 dev build until I updated to Moodle 20181031 build. Now upon trying to activate the theme I get the following debug info.
=======================================
Sorry, the requested file could not be found

Debug info: block_myoverview/progress-chart
Error code: filenotfound
Stack trace:

    line 125 of /lib/classes/output/mustache_template_finder.php: moodle_exception thrown
    line 54 of /lib/classes/output/mustache_filesystem_loader.php: call to core\output\mustache_template_finder::get_template_filepath()
    line 99 of /lib/mustache/src/Mustache/Loader/FilesystemLoader.php: call to core\output\mustache_filesystem_loader->getFileName()
    line 82 of /lib/mustache/src/Mustache/Loader/FilesystemLoader.php: call to Mustache_Loader_FilesystemLoader->loadFile()
    line 657 of /lib/mustache/src/Mustache/Engine.php: call to Mustache_Loader_FilesystemLoader->load()
    line 184 of /lib/outputrenderers.php: call to Mustache_Engine->loadTemplate()
    line 1245 of /theme/fordson/classes/output/core_renderer.php: call to renderer_base->render_from_template()
    line 219 of /lib/mustache/src/Mustache/Context.php: call to theme_fordson\output\core_renderer->teacherdash()
    line 138 of /lib/mustache/src/Mustache/Context.php: call to Mustache_Context->findVariableInStack()
    line 54 of /home/digics5/mdldev_data/localcache/mustache/1541160597/fordson/__Mustache_6131cbbd867094d795d02418831a833a.php: call to Mustache_Context->findDot()
    line 67 of /lib/mustache/src/Mustache/Template.php: call to __Mustache_6131cbbd867094d795d02418831a833a->renderInternal()
    line 191 of /lib/outputrenderers.php: call to Mustache_Template->render()
    line 76 of /theme/fordson/layout/columns2.php: call to renderer_base->render_from_template()
    line 1287 of /lib/outputrenderers.php: call to include()
    line 1217 of /lib/outputrenderers.php: call to core_renderer->render_page_layout()
    line 51 of /theme/index.php: call to core_renderer->header()

**Comment by dbnschools** [comment]
This could be because they are breaking up the course overview and stuff from the Dashboard.  Fordson borrows one of these template files to render the radial course completions.  Thanks for reporting.  We will take a look.

**Comment by dbnschools** [comment]
Our plan is to wait until after 3.6 is released to apply fixes and patches for Fordson.  There are too many changes with Boost and Dashboard Blocks to keep up.  We want to wait until it is finalized.  With that said, I am actively tracking and making changes.  
This issue is because Boost is moving away from the radial and towards a simple progress bar.  Early next week I should have a fix.  I am removing the radial completion from showing up on course tiles on the site home page.
What is really exciting is the work Moodle HQ is putting into the Dashboard.  We are re-focusing on making the Dashboard more of a priority and will be reconsidering what purpose the site home should server.  I am beginning to think the Dashboard will be our landing page.  Not quite sure just yet.

**Comment by dbnschools** [comment]
Latest release as of 11-7-18 and this should fix some of the new changes to Boost: 

https://drive.google.com/file/d/1cc2_pl6IM9F0BMugh1Fh_peIDyPJFG2_/view?usp=sharing

**Comment by dbnschools** [comment]
I don't want to publish anything as it can still change but also because I really need to fix the new dashboard default images.  I need to get it to use the Fordson default images
![dashboard](https://user-images.githubusercontent.com/28066305/48156174-cd2e3a80-e29a-11e8-9588-d702ca4c7ed8.png)

**Comment by bollycanuk** [comment]
Chris,

Thanks for the update to the theme. It works very well with the 11/7 Moodle
3.6 core update.

cheers,
Derek

**Comment by bollycanuk** [comment]
It just needs,,,, MORE COWBELLS!

**Comment by dbnschools** [comment]
If that would help students learn it would ship with them!  lol.

**Comment by bollycanuk** [comment]
I've noticed that the Modern & Pulse theme presets don't seem to use the
Content padding setting in the Preset adjustments whereas all the other
presets do. Is this by design? If so it's a bit confusing.

**Comment by dbnschools** [comment]
Fordson is now fully working on Moodle 3.6 and has been released.  Closing this thread.
