### ISSUE TITLE
"Site announcements" string is not translated

### ISSUE THREAD

**Issue by ianni67** [dbnschools/moodle-theme_fordson#45]
As per subject: the string "Site announcements" in the home page is not translated when I change language to italian. All other strings are correctly translated. The "sitenews" string is present in the the language pack.

I really like this theme but could not find a solution to this issue.

**Comment by dbnschools** [comment]
I will take a look and get this fixed.  Do you have a screenshot of the exact place the text isn't translating?  Also, what version of Moodle and Fordson theme are you using?

**Comment by ianni67** [comment]
Thank you for your prompt reply.
Moodle: $release  = '3.5.2+ (Build: 20181023)'
Fordson: 3.5 (downloaded and installed abt one week ago).
![screenshot_20181103_095135-01](https://user-images.githubusercontent.com/15045704/48156589-1055d100-e2ce-11e8-8876-08fe0193590a.png)

**Comment by dbnschools** [comment]
Thanks for the image.  That language string is translated by Moodle and part of core.  It is not generated at the theme level.  This message will not change unless the user selects another language from Moodle and the proper language is set at the site/user level.

**Comment by ianni67** [comment]
This is the only string that does not change when the user selects another language. I already tried everything I now to select a language. Would you, please, elaborate a little bit more on "the user selects another language from Moodle"?
Thank you very much for your kind help

**Comment by dbnschools** [comment]
I have searched throughout my theme to find that as a text string or just hard coded and I cannot find anything.  Does it do the same thing with the Boost theme?

**Comment by ianni67** [comment]
I just checked. Indeed it does the same thing with the Boost theme. It must be an issue with my configuration, though it is a fresh install and I cannot figure out what it may be. 
Sorry, I did not realize it was a moodle-wide issue in my installation. 
Thank you for your help. I suppose that now the issue can be closed.

**Comment by dbnschools** [comment]
It might be a bug with Moodle core.  It's possible that that string wasn't translated.

**Comment by ianni67** [comment]
The corresponding string in the italian "lang" dictionary is present. The problem is that it is not picked up by moodle.

**Comment by ianni67** [comment]
I eventually stumbled upon this page, describing exactly the same issue: [https://moodle.org/mod/forum/discuss.php?d=353045](https://moodle.org/mod/forum/discuss.php?d=353045)
Looks like it is a long-living problem in moodle. Never solved.

**Comment by dbnschools** [comment]
OK.  Looks like this is a Moodle issue and not the theme. Closing.
