### ISSUE TITLE
Moodle 3.4.6 Can not Login due to missing LoginToken

### ISSUE THREAD

**Issue by ruddj** [dbnschools/moodle-theme_fordson#48]
Moodle 3.4.6 introduced a requirement that all login forms have a logintoken attribute to prevent automated logins.
https://docs.moodle.org/dev/Login_token

As Fordson 3.4 v1.7 is missing this line, after performing the upgrade users are unable to login.

This can be easily fixed by adding
`<input type="hidden" name="logintoken" value="{{logintoken}}">`
after lines 117, 162, 227, 270,
https://github.com/dbnschools/moodle-theme_fordson/blob/moodle34/templates/core/login.mustache#L227

**Comment by dbnschools** [comment]
I am backporting the fix for Moodle 3.5.3 and will have a new version for 3.4 up soon.  Moodle.org is where I'll be publishing the fix.  Moodle.org was having an issue with uploading new plugins yesterday.  I reported it and they said they would fix the issue.  should have it ready to go today.

**Comment by ruddj** [comment]
Thank you. I tried to create a backport with pull request, but I could have easily missed things.

**Comment by ruddj** [comment]
Will you be updating the GitHub moodle34 branch in addition to posting on moodle.org?

**Comment by dbnschools** [comment]
I pushed the changes I made to the Moodle34 branch.

**Comment by ruddj** [comment]
Thank you.
