### ISSUE TITLE
Quiz: answer separator

### ISSUE THREAD

**Issue by fxpar** [dbnschools/moodle-theme_fordson#5]
Hi, 

A visual guide to group the choices in the quiz could help when editing questions:

````html
		<div class="form-group row  fitem  " id="yui_3_17_2_1_1499593320543_930">
    <div class="col-md-3">
        <label class="col-form-label d-inline " for="id_answer_0" id="yui_3_17_2_1_1499593320543_673">
````

		

![image](https://user-images.githubusercontent.com/11584406/27992765-bc5aaee2-649b-11e7-8b92-aec6b4b9b403.png)

In essential theme it looks like:
![image](https://user-images.githubusercontent.com/11584406/27992812-e7ec0046-649c-11e7-81da-eeb4ec4bef94.png)

Thanks again for this very nice theme

Regards

François

**Comment by dbnschools** [comment]
What question type is this?

**Comment by dbnschools** [comment]
Unfortunately without re-writing the renderer I do not see a css element I can style to make this change.

**Comment by fxpar** [comment]
Hi, 

It is a multiple choice.
I understand. I don't know how Essential did it either. 
Thank you for looking it up.

François
