### ISSUE TITLE
Custom menuitems from navbar to nav-drawer on mobile?

### ISSUE THREAD

**Issue by marniemi** [dbnschools/moodle-theme_fordson#51]
Love the theme!
But for me it would be even better if issue with menuitems could be resolved.

If I use site with mobile phone, custom menuitems are transfered from navbar to the bottom of the footer. That means a scroll of death to access those links. Could those links be transfered to nav-drawer instead for easier access.

Jump-to-section dropdown menu is not showing to the guest users. Can I make it visible somehow?

**Comment by dbnschools** [comment]
1) The custom menus follow the design of Boost.  Moving the links to the bottom on mobile is the default behavior.  Moving them to the sidebar would only clutter that area up and it would be more work than you'd imagine to do so.  Especially if you have lots of links.  Personally, we do not use custom menus.  We want students focused on what the teacher wants them to do in the course and not all these links to take them out of the course.

2)  I've not witnessed the jump section menu being hidden.  But I've never looked to pay attention.  Is it hidden with Boost theme too?  Fordson will inherit most default behaviours of Boost.

**Comment by marniemi** [comment]
Thanks for Your comments. I managed to bypass the first one by adding links to nav-drawer with JQuery in additional-HTML. The second one became irrelevant with this too.
