### ISSUE TITLE
Link "Create a course" (front page) is hard coded and wrong sometimes

### ISSUE THREAD

**Issue by salex-uriel** [dbnschools/moodle-theme_fordson#52]
Categories do not always start from ID = 1.
The link being hard coded, when I want to add a course right from the front page, generates obvious error: 

> Can not find data record in database table course_categories.

**Comment by dbnschools** [comment]
Good call.  I might have to add a url text box in the site settings just in case you delete the default category or want to change it to something else.  I'll try to get it added for the Moodle 3.6 release but if not shortly thereafter.

**Comment by dbnschools** [comment]
Sorry, I should have checked my settings page first.  You can totally customize the URL and have been able to do so for quite some time.  It is not hard coded as you suggest.  It does default to using category=1 but on the Icon Navigation Tab of Fordson you can use whatever link you want.
  
![moodle 3 6 dev administration appearance themes fordson](https://user-images.githubusercontent.com/28066305/49740796-00c9ff00-fc63-11e8-9885-b312eb3bf5dd.png)

**Comment by dbnschools** [comment]
In fact, you can make this link go to something completely different and it will only show up for users who are course creators at the site level.  I designed it with this purpose in mind so that you can customize it.
