### ISSUE TITLE
Course tile scrollbars not sized correctly on laptop

### ISSUE THREAD

**Issue by ChristopherKingChemist** [dbnschools/moodle-theme_fordson#54]
On the home page for users who are not logged in I have three course tiles displayed.  The image in the tiles is not very high, so I increased the size of the course tile height (the “courseboxheight” parameter ) from the default 200 px to 400 px.  That displayed much more (if not all) of the images.  However, I noticed the scrollbars were not displayed correctly in either case.  In the 200 px high tile the scrollbar is cut off at the bottom.
200 px courseboxheight:
![jordson course tile scroll bar 200 px](https://user-images.githubusercontent.com/34283059/49690312-4ddb9300-faf4-11e8-8fff-92d8c143a714.PNG)
In the 400 px high tile the scrollbar does not extend to the bottom of the tile.
400 px courseboxheight:
![jordson course tile scroll bar 400 px](https://user-images.githubusercontent.com/34283059/49690315-5fbd3600-faf4-11e8-8f9c-86b2e0aee8bb.PNG)
This problem is visible on my 1366 × 768 laptop.  I haven't confirmed this problem on a larger monitor, yet.  The image itself is 800 × 533.

**Comment by dbnschools** [comment]
What Moodle version, fordson version, and browser are you using?  If there is too much information it will use scroll bars to fit the content.  However, we styled the scrollbar for chrome/firefox.  We only test on firefox and chrome.

**Comment by ChristopherKingChemist** [comment]
Using Moodle 3.6.1, Firefox, the latest Jordson, theme preset "Spectrum-achromatic", course tile display "Tile Style Four W/Course Summary".

**Comment by dbnschools** [comment]
My initial suggestion is to increase "Course Tile Height" to be higher than 200px (on the preset adjustment tab in Fordson theme admin).  Default is 250px and that will solve the issue for you.  You made the tiles too small.  My other suggestion is to get rid of the main menu block.  You can include that text in the custom textbox of the page if needed.  It takes up valuable screen space.  You might also want to utilize a different tile display option if you have too much text or are not getting the results you want.  Course tile height is set too small.  Increase this via the drop down.
