### ISSUE TITLE
Adjustments to text input activity names

### ISSUE THREAD

**Issue by cgrantmccool** [dbnschools/moodle-theme_fordson#55]
I'm sorry to come to you with this, but I have had zero luck with the development tracker proper and am now hoping to maybe do this on my own or to try to help the theme we use incorporate a feature. I've found the documentation for how to make the text area act how I want, I just can't find where to do this. Plus, you've incorporated several of my requests into your theme, before and I think this may be a useful feature for your school district's foreign language classrooms, especially any that are AP or immersive.

Our Moodle site is predominantly focused on revitalizing a Native American language. As such, we have some characters that need to be in Assignment/Page/Book/etc titles and names but that text box is extremely limited. Specifically, we just need to allow for underlined letters.

[Sample Issue - Glossary Entry: ](https://classroom.samishtribe.nsn.us/mod/glossary/view.php?id=228&mode=letter&hook=X&sortkey=&sortorder=)   

Our current work around is a Unicode tool, copy and paste, but that isn't functional for our users in the long term. https://classroom.samishtribe.nsn.us/mod/page/view.php?id=118

I'm trying to first make the "Concept Entry" box an ATTO editor and then adjust that instance of the ATTO to only the features we would need for inputting the Samish Language. Next I'm hoping to do the same to the Lesson Name (those two cover 90% of my current needs), and then continue with this change throughout the rest of the template fork.

The lack of update by the moodle community on this area baffles me, a little bit, given the amount of internationalization and coding for language expansion Moodle has gotten over the past two years. Again, I also apologize for coming to you on this, I've had no luck on the regular dev tracker.

**Comment by dbnschools** [comment]
I'm not sure I can help you.  I believe there are others more qualified who might be found in the language forums/portals of Moodle.
