### ISSUE TITLE
Color sectors not showing default values

### ISSUE THREAD

**Issue by ChristopherKingChemist** [dbnschools/moodle-theme_fordson#56]
Christopher,
The color selectors work just fine, but the default colors do not show for those color selectors.  Here's what I see:
![image](https://user-images.githubusercontent.com/34283059/50728250-81f2a580-10ec-11e9-9cf5-bdba99f8e6e9.png)
I see that wherever there is a color selector.  The default colors do show up; they just aren't listed in the box. Is that what you see, too?  If it works for you, then the problem is likely with my setup.
Chris

**Comment by dbnschools** [comment]
This is normal.  The colors are actually set initially in the SCSS file.  I don't load any default colors because these are overrides to the colors in the Presets.
