### ISSUE TITLE
Using Fordson on Moodle 361 - Feature request

### ISSUE THREAD

**Issue by Tigger996** [dbnschools/moodle-theme_fordson#57]
I just started looking at Fordson.  I love the buttons on the right that popup with course admin functions etc.  Could you have the Site Admin button do the same thing?  It would be way easier to navigate to Admin settings without having to go to the main site admin page first. And if the button could do that.  When logged in as admin to have the button available on all places throughout the site.

Thanks.

**Comment by dbnschools** [comment]
Unfortunately we cannot.  We are all about making things easier for the teacher/student but something like this would be a lot of work to benefit one person on the site.   We are all about improvements to make learning better and easier but the site admin (Me included) can suffer through it.  

Thanks for the suggestion and if you have any in the future please share them.
