### ISSUE TITLE
Error logging in as guest

### ISSUE THREAD

**Issue by izendegi** [dbnschools/moodle-theme_fordson#58]
Hi,

I'm trying to enable guest access in a Moodle site following the docs [1] in a Moodle 3.6.1 with Fordson v3.6 release 1.1, but when I click on the 'Log in as guest' button it throws back a "Invalid login, please try again" message.

Changing the theme to Boost the button works as expected, so I guess it is something related to Fordson.

I've tried both the standard login and the custom Fordson login (showcustomlogin), and the error happens anyway.

[1]: https://docs.moodle.org/36/en/Guest_access

**Comment by dbnschools** [comment]
<input type="hidden" name="logintoken" value="{{logintoken}}">
This line was missing.

**Comment by dbnschools** [comment]
Fixed in Version 1.2 for Moodle 3.6
