### ISSUE TITLE
Css for blocks submit buttons

### ISSUE THREAD

**Issue by fxpar** [dbnschools/moodle-theme_fordson#6]
Hi, 

One of my block has a submit button. For now it is rendered with an old html button.
Could we add some css to embellish it?

```html 
<button type="submit">Reset theme cache</button>
```

![image](https://user-images.githubusercontent.com/11584406/27992721-db05a73a-649a-11e7-9797-b6366ca11033.png)

In essential theme it looks like
![image](https://user-images.githubusercontent.com/11584406/27992799-8de4068e-649c-11e7-931e-5025944dc10d.png)

Regards
François

**Comment by dbnschools** [comment]
You can add your own CSS to the custom CSS Box within Fordson to make the button look better.  If you want to share that code with me I can include this into theme.  I suspect Boost also displays the button this way.
