### ISSUE TITLE
[Improvement] Customize resources and activities when Custom Chooser enabled

### ISSUE THREAD

**Issue by izendegi** [dbnschools/moodle-theme_fordson#61]
We have the resource/activity Fordson custom chooser enabled (we call it "Most used"), but we keep other resources and activities visible, and in that scenario we would like to customize the "Resources" and "Activities" labels (makes more sense to us to be "Other Resources" and "Other activities").

**Comment by dbnschools** [comment]
You can use the Built in Moodle Language editor to change the names of those labels.  That is the best and easiest way to handle this.  No plugin required.

**Comment by izendegi** [comment]
That's a good workaround (we've already applied that), in that way there is no need of any plugin, thanks!

Anyway, I still think you should consider to use another strings together with the custom chooser, because with some activity&resources on the custom chooser those sections wouldn't be "Resources" and "Activities" any more and "other" "rest of" or similar should be added to be accurate.
