### ISSUE TITLE
Generico in course Dashboard

### ISSUE THREAD

**Issue by dairaine** [dbnschools/moodle-theme_fordson#63]
Hello,

I have an issue with Fordson. We are usgint Generico filter in the course description fields. Generico filters seems not supported in the displayed  "Course Description",   when the learner clics on the Course Dashboard.
Thanks.

**Comment by dbnschools** [comment]
Sorry.  We do not use that plugin and do not have the resources to look into this at the moment.  If you discover a fix or solution please let us know and we can try to work that into the theme if it is indeed a theme issue.
