### ISSUE TITLE
InvalidParameter error - only on Administration pages

### ISSUE THREAD

**Issue by richardschwarz** [dbnschools/moodle-theme_fordson#64]
Hi there. Upgraded Moodle to 3.6.2 and running the latest Fordson from the plugins directory. Now I am getting an InvalidParameter warning on all administration pages (including course administration) on every load - which is a little frustrating. It doesn't appear to exist on course pages or the front page/login pages at all. Our theme is using 'Modern Moodle'.
![invalidparameter](https://user-images.githubusercontent.com/145715/51910230-59737800-241a-11e9-820e-a3de952c56ad.png)

Ideas? What extra information do I need to pass on?

**Comment by dbnschools** [comment]
Try going to Fordson theme settings and just click the save button at the bottom.  It is possible during the update a setting was not saved.  Also, what other plugins do you have installed?  Finally, please clear caches on Fordson.

**Comment by richardschwarz** [comment]
Hi Chris. I've cleared cache and removed my custom css, cleared cache and also tried the save thing. Unfortunately, none of that solved the issue. I've tried other themes and they all seem to work without the invalidparameter error. I did notice that a few fontawesome icons (I think) are not showing - see picture attached. It's a bit weird as it's only in the settings area... not standard course pages.
![fordson-no-fontawesome](https://user-images.githubusercontent.com/145715/51982043-a4f05980-24e0-11e9-826a-b9f1759844b7.png)

**Comment by richardschwarz** [comment]
Have removed Fordson, cleared all caches, reinstalled Fordson clean, and it appears again. Hmmm. Confusing

**Comment by dbnschools** [comment]
It might have been a cache issue on either server or browser.

**Comment by richardschwarz** [comment]
Unfortunately not. It is also happening on all teacher accounts when they go to Course Administration (so not just Site Administration). I've deleted plugins, removed and re-installed Fordson, removed custom css, and I'm not sure what it is... seems to be something being called only on an admin page.

**Comment by dbnschools** [comment]
It seems like maybe this is related to the Moodle upgrade if it is happening when Fordson and plugins are uninstalled.

**Comment by richardschwarz** [comment]
About to try a separate vanilla install of 3.6.x and Fordson and then
plugins 1 by 1 to see if they're the cause. I'll post back with results

Thanks,
Richard

**Comment by dbnschools** [comment]
Did you have any success?  I'd like to know if it was a plugin issue or not.

**Comment by adriano515** [comment]
Happens in 3.7 fresh install as well, i have the following external plugins installed: 

- local_codechecker
- format_etask
- availability_coursecompleted
- qtype_wordselect
- qtype_kprime
- qtype_gapfill
- mod_game
- mod_choicegroup
- mod_checklist. 

Uninstalling the external plugins did not fix it. 

Activating debug mode shows the following: 

![imagen](https://user-images.githubusercontent.com/13358744/58119828-261f4980-7bc1-11e9-9f8f-e8ac48ab5ff9.png)

![imagen](https://user-images.githubusercontent.com/13358744/58120469-8ebaf600-7bc2-11e9-9cb5-8506bfccc1af.png)


Additionally it was working fine until i (as admin) enrolled in a course , then went to website/moodle/my and tried filtering and sorting the course.

**Comment by dbnschools** [comment]
It's got to be one of the plugins.  I don't have these issues and cannot
reproduce them.

**Comment by dbnschools** [comment]
I don't believe this is related to Fordson.
