### ISSUE TITLE
Unable to fully empty alertbox using atto

### ISSUE THREAD

**Issue by izendegi** [dbnschools/moodle-theme_fordson#68]
I've shown a alert using the alertbox field of Fordson, and when I've wanted to delete it I've seen that the orange background is still shown up in the homepage.

I've seen that the reason of that is that when editing a HTML field with the default editor (atto), if an edited field is empty it is automatically filled in with `<p><br></p>` and therefore Fordson keeps showing up the alert background colour.

I'm pretty sure this isn't a Fordson issue but a Moodle core (atto) issue, but its effects are relative to Fordson so a workaround may be done here.

**Comment by dbnschools** [comment]
You will want to turn on HTML view and then delete the code there and save it.

**Comment by izendegi** [comment]
I've tried that but didn't work, it seems like atto adds that code in a text-validation trigger or similar, even if you delete the code in the HTML view. 

The only way I found to workaround this was to change the text-editor in my profile to plain-text editor and then deleting it.

**Comment by dbnschools** [comment]
let me see if I can apply the styling differently to fix this.

**Comment by dbnschools** [comment]
What version of Fordson and Moodle?  I am trying to recreate this issue and I cannot do so on my dev site.  Moodle 3.6.2 is what I have.

**Comment by izendegi** [comment]
I'm also using Moodle 3.6.2 with Fordson v3.6 release 1.2.

I've disabled all non-standard atto plugins and it still happens (you have to save some text and then delete it to make it happen). 

Anyway, any Moodle admin should be able to use the workaround, so this issue can be forgotten...
