### ISSUE TITLE
[reminder] Three old pull requests

### ISSUE THREAD

**Issue by izendegi** [dbnschools/moodle-theme_fordson#71]
I've seen that three small fixes I sent some weeks ago haven't been integrated or refused, you may haven't seen them so (just in case) I link them here:

https://github.com/dbnschools/moodle-theme_fordson/pull/69
https://github.com/dbnschools/moodle-theme_fordson/pull/66
https://github.com/dbnschools/moodle-theme_fordson/pull/65

**Comment by dbnschools** [comment]
I've looked at these and implemented them.  Thank you for contributing back to the project.
