### ISSUE TITLE
Where is version v1.6.6?

### ISSUE THREAD

**Issue by fredcy** [dbnschools/moodle-theme_fordson#72]
I'm currently using Fordson version v.1.6.5 on a Moodle 3.3.9 system, and I'm getting an admin notification that version v1.6.6 is available.  But I can't find that version in the git repo with https://github.com/dbnschools/moodle-theme_fordson.git as origin. Is it there in some commit? How can I get to it?  

I see that version v1.6.6 is available via the 'Download' link, but I manage all my plugins via git.

![Screen Shot 2019-04-24 at 3 56 41 PM](https://user-images.githubusercontent.com/15950/56693278-ac6f6b00-66a9-11e9-99e5-2a649a3e2a5c.png)

**Comment by dbnschools** [comment]
I might not have published it on Git.  Sorry.
