### ISSUE TITLE
The 'Course completion' bar shows in the 'Available Courses' listing when not logged in.

### ISSUE THREAD

**Issue by Robynstar** [dbnschools/moodle-theme_fordson#73]
Which I am assuming shouldn't be happening when there's not a user to show the progress for!
Affected Course Tile Displays: Tile Style Three, Corporate Training

**Comment by dbnschools** [comment]
I added a check to make sure the user is logged in before displaying the %.  It will be in the next release.  Thanks for finding this.

**Comment by dbnschools** [comment]
Fixed and posted on github in M37 1.1 release.  Will be on Moodle.org soon after a few more things fixed.
