### ISSUE TITLE
Missing quote in dashboard template

### ISSUE THREAD

**Issue by Robynstar** [dbnschools/moodle-theme_fordson#74]
https://github.com/dbnschools/moodle-theme_fordson/blob/f9909ee10745c0d3ea2ff6090b2172383af97a7c/templates/teacherdash.mustache#L209
There is a quote mark missing from the start of the class:
`<div class=col-md-12 studentprogress">`
....................^
which means it it coming up in html as 
`<div class="col-md-12" studentprogress"="">`

**Comment by dbnschools** [comment]
fixed in M37 1.1 release just posted on github.  Will post to Moodle.org after a bit more work.
