### ISSUE TITLE
Firefox browser issue

### ISSUE THREAD

**Issue by cprudhoe** [dbnschools/moodle-theme_fordson#75]
I am using Moodle 3.7+ (Build: 20190606)
I opened Moodle using the Fordson theme in Firfox browser and found an issue.
The login form fields are blank and you can't see where to enter your username and password.
This works in Chrome, Wedge, and Opera browsers but not in Mozilla Firefox.
![FirefoxIssue](https://user-images.githubusercontent.com/13261250/59570096-7969a800-9058-11e9-953c-a57bb02ec79c.png)

**Comment by dbnschools** [comment]
I cannot reproduce this issue.  I'm thinking you might have changed some items on a core file.  Namely the one which indicates the issue in /login/index.php.  It says line 433 but on my 3.7 site the login/index.php file ends at line 370.  You got something else going on here and I don't believe it is related to the Fordson theme.
