### ISSUE TITLE
 Fordson theme tab navigation error

### ISSUE THREAD

**Issue by maxblueman** [dbnschools/moodle-theme_fordson#76]
I'm using Moodle 3.6.4 with the theme Fordson v3.6 release 1.3.1
I came across an error in site administration in the appearance section / theme / fordson. The tab navigation is not working. Is there any fix for this error?
![error](https://user-images.githubusercontent.com/2979725/59708585-71864100-91db-11e9-95cd-578dd0c8af79.jpg)

**Comment by dbnschools** [comment]
What else do you have installed or customizations have you done?  I've never encountered this error or issue.

**Comment by maxblueman** [comment]
I installed several plugins and themes to test. I do not know if this is influencing. The installation was carried out in the development environment of the company where I work. In fact this error happens in other themes like Moove, Trema, Klass.

**Comment by dbnschools** [comment]
So it is not related to Fordson but rather a plugin or possibly some other issue on yoru server.
