### ISSUE TITLE
"Activities/Resources" menu - file apperance is locked

### ISSUE THREAD

**Issue by acquaalta** [dbnschools/moodle-theme_fordson#77]
Hi,
First, thanks for the great theme :-)

Regrading the setting "Customized activity and resource modules" (theme_fordson | commonlyused), I noticed the following things:
1) If there is a list of activities, it doesn't matter where exactly I insert "file", its location in the "Add an activitiy or resource" menu stays the same.
2) Even if I don't insert "file" into the setting, but insert "resource" instead, what is actually happens in the UI is the display of the "File" resource. So I don't understand what's the meaning of "resource" in this context, and why "File" is shown instead.

Could you please check this issue? Maybe I'm missing something.

**Comment by hasqld** [comment]
I think this is because the options available in that setting need to be the names Moodle uses for each type.
Moodle's name for the "File" type is actually "resource".
So "file" is not a even a valid option and you need to use "resource" instead.

**Comment by acquaalta** [comment]
Thanks for the quick response.
So you should maybe consider updating the text in the "theme_fordson | commonlyused" settings.
Right now it includes the following:
"DEfault Resources:
book,file,folder,imscp,label,page,resource,url".

I also emphasised the "DE" in "Default Resources", which seems to be unintentional. I assume that only the first letter need to be capitalized.
And since it's not clear to the user, maybe you should write something about "resource" being the codename for the "File" option in Moodle.

So If I understand correctly, the "file" in this list has no use?

On Wed, Jun 26, 2019 at 2:57 AM IT Dept at Hillbrook Anglican School <notifications@github.com<mailto:notifications@github.com>> wrote:

I think this is because the options available in that setting need to be the names Moodle uses for each type.
Moodle's name for the "File" type is actually "resource".
So "file" is not a even a valid option and you need to use "resource" instead.

**Comment by hasqld** [comment]
They all sounds like very sensible suggestions.
I'm just another user of this theme who happens to utilise and love the "commonly used" options.
I'm sure, however, the developers will see this thread and take on your suggestions.

**Comment by dbnschools** [comment]
Thanks.  I have the lang string fixed for the next release.  Resources include the following:  Book, file, folder, label, page, url.  In the lang string I removed the word 'resource' from the defaults.  Must have ended up there by mistake.

**Comment by acquaalta** [comment]
> Resources include the following: Book, file, folder, label, page, url. In the lang string I removed the word 'resource' from the defaults. Must have ended up there by mistake.

Maybe I'm missing something, but isn't the opposite way? - The text "file" should be removed from the lang string, and "resource" should be used instead.

Please see above hasqld's comment from July 26th, 2019. He says that Moodle's name for the file resource is "resource" and not "file". I checked it in the custom menu context, and it seems true.
