### ISSUE TITLE
Upload setting for Favicon

### ISSUE THREAD

**Issue by eSrem** [dbnschools/moodle-theme_fordson#8]
Hi there,

What would your opinion be on adding support to upload a favicon?

Cheerful regards,

Virgil

**Comment by dbnschools** [comment]
It's on a list of ideas for improvement.  However, we just got the majority of features we wanted implemented and now we are focusing on the style presets.  If you noticed the last two updates included some new presets.  I have been working on a special preset called Dearborn Public Schools in the v1.6.0 release.  This will eventually move to the default spot in a future update.  Once we get that preset looking smooth I need to spend time cleaning up the code - a lot of time!  

Once that is all said and done I hope to revisit more features like this one.  My next goal is to get things ready for Moodle 3.4 and that is where I will be focused in the near term with this theme.

**Comment by dbnschools** [comment]
PS.  If you have code or want to contribute the solution to get the favicon upload working with Fordson I would be glad to take a look.

**Comment by dbnschools** [comment]
eSrem,
Version 1.6.3 of the Fordson theme now includes a favicon upload feature.  Just put the version up on Moodle.org.
