### ISSUE TITLE
Course page - Is it possible to turn off the clickability of the course title? 

### ISSUE THREAD

**Issue by acquaalta** [dbnschools/moodle-theme_fordson#81]
Hi,
In a course page, is it possible to turn off the clickability of course title? 
In many cases, while documenting some actions in the system, I need to copy the current course name. It's a little bit hard to select the course name and copy it, because the course title is clickable - instead of clicking the text in order to copy it, the user have to select the text from the beginning to the end. 

Is it possible to turn this functionality off, somehow?

![Fordson - Course page - The course title is clickable](https://user-images.githubusercontent.com/51836675/61353319-2877ea00-a878-11e9-90ac-f50e1ad2c5c1.png)

**Comment by dbnschools** [comment]
You can edit the renderer in core_renderer.php  https://github.com/dbnschools/moodle-theme_fordson/blob/master/classes/output/core_renderer.php#L75-L77

That is what you'd want to change.  While it might make your job slightly more difficult, this is a huge usability improvement for students and teachers who use the course to easily get back to the main page of the course.  We won't be removing it.  Our staff requested it.  But it is an easy enough fix by altering the code I highlighted above if you wanted to modify your site.
