### ISSUE TITLE
Urgent:  Moodle 3.7.1 course setting menu permission issue

### ISSUE THREAD

**Issue by Tigger996** [dbnschools/moodle-theme_fordson#83]
I have an issue where a user with a teacher role in a course cannot see the course setting menu under course management.

I switched the course theme to Boost and was able to see the edit settings option from the cog.
So it has something to do with the theme.  

If I switch the user to manager in the course (just for testing), the course setting menu appeared.

Please advise.

**Comment by dbnschools** [comment]
$hasteacherdash = has_capability('moodle/course:viewhiddenactivities', $context);
Don't mess with teacher role permissions!  You disabled their ability to do backups.  This is the permission we use to determine if a teacher can view the course management links.  See the code here:  https://github.com/dbnschools/moodle-theme_fordson/blob/master/classes/output/core_renderer.php#L1483-L1487

If you disable any of these then it will affect what the teacher can see. Enable course backups for teachers and the links will appear.

**Comment by dbnschools** [comment]
PS.  I am at the Mountain Moot in Montana right now.

**Comment by Tigger996** [comment]
Thanks for the quick response!

So I have to enable backups for teachers to see the whole menu?  I don't want to allow my teachers to do backups.  It's off for a reason :)

I can turn it on for now so that it doesn't impact them while they are getting their courses ready for fall, but could there be a better fix?

Thanks again
