### ISSUE TITLE
Grader report with 'fixed' columns Firstname/Lastname

### ISSUE THREAD

**Issue by giselebrugger** [dbnschools/moodle-theme_fordson#84]
Moodle: Moodle 3.6.2+ (Build: 20190118)
Fordson: v3.6 release 1.3.1 2019111003

a suggestion:

when teachers scroll horizontally and the gradebook is too big to be displayed in a full screen the first name / lastname column should be fixed as in the boost theme.

see https://youtu.be/RSs2ZLhWGsU

**Comment by dbnschools** [comment]
hmm... we've not seen this issue.  It doesn't do this in our gradebook.  Are you using some gradebook plugin?  I've seen where they can break stuff.
