### ISSUE TITLE
Mismatched anonymous define call throws error to browser page

### ISSUE THREAD

**Issue by richardjonesnz** [dbnschools/moodle-theme_fordson#87]
As reported at Moodle previously.

Moodle 3.6.1, Theme Moodle 3.6 Fordson v3.6 release 1.3.1 2019111003.

Image of the console error is here: https://moodle.org/mod/forum/discuss.php?d=389579

Will sometimes throw the error message over the browser page causing confusion to users.

**Comment by dbnschools** [comment]
This appears to be related to a calendar widget.  Are you sure it is theme related.  I am unable to reproduce this no matter how hard I try.

**Comment by richardjonesnz** [comment]
It appears when Fordson is selected but not when Boost is selected.  However, I can't reproduce on a test site either so it's probably a conflict with some other installed widget as you say.  Sorry, should have checked that first.
