### ISSUE TITLE
Lesson module progress bar missing styling

### ISSUE THREAD

**Issue by Vitbok** [dbnschools/moodle-theme_fordson#9]
We get this:
![image](https://user-images.githubusercontent.com/19798904/31997802-fd97fa3c-b995-11e7-8b4a-9f5a036cbcc7.png)
instead of this:
![image](https://user-images.githubusercontent.com/19798904/31997856-23bd6148-b996-11e7-822b-360cb72c64fe.png)
Here's the missing CSS code:
```
.path-mod-lesson .progress_bar_completed {
    background-color: green;
    text-align: right;
    vertical-align: middle;
    color: #fff;
}
```

**Comment by dbnschools** [comment]
Check version 1.6.0.  I added your code in the styles.php   

https://github.com/dbnschools/moodle-theme_fordson/blob/master/scss/styles.scss#L735
