### ISSUE TITLE
Fordson + Pulse + Section Style: Highlighted Section Title --> progress bar position strange

### ISSUE THREAD

**Issue by yorickreum** [dbnschools/moodle-theme_fordson#90]
In the screenshot you can see a clean Moodle installation with clean Fordson. All settings are default, but "preset" is set to "Pulse" and "sectionlayout" is set to "Highlighted Section Title".
I don't think the current position of the progress bar is intended, is it?

Kind regards from Germany
Yorick

![image](https://user-images.githubusercontent.com/39629166/64188438-b5035980-ce72-11e9-970e-0d3a0646bbeb.png)

**Comment by dbnschools** [comment]
I have a fix.  Will be in next release.  Just add this to the sectionstyle6.scss file:
.progress.fordsonsinglepage {
    margin-top: 1rem;
    margin-right: 1rem;
}
