### ISSUE TITLE
Grading header on background image obscures vital text

### ISSUE THREAD

**Issue by richardjonesnz** [dbnschools/moodle-theme_fordson#93]
![fordsondoc](https://user-images.githubusercontent.com/2015917/68444158-e44f9180-023a-11ea-99b8-058d2521a59c.PNG)

I feel like this div should have an opaque background but I don't believe it's accessible via css?

**Comment by dbnschools** [comment]
What version of Fordson and Moodle?   
Also, What are the settings on the Preset Tab of Fordson theme admin?

**Comment by richardjonesnz** [comment]
Thanks for the quick response, we have:

Moodle 3.6.1+ (Build: 20181220) 
Fordson v3.6 release 1.3.1 2019111003.

The preset is Boost, Default Boost, Corporate Learner, Simplicity and Single Column Boost Default

**Comment by dbnschools** [comment]
This will fix the issue for you:
.path-mod-assign [data-region="grading-navigation-panel"] {
    background-color: #fff;
}

.path-mod-assign [data-region="grade-actions"] {
    background-color: #fff;
}

Just copy and paste this into the Custom SCSS box at the bottom of the Fordson Color Tab in the admin area.

**Comment by richardjonesnz** [comment]
Thanks.
