### ISSUE TITLE
Login dialog hidden by Slideshow using latest Fordson 3.7 theme with Moodle 3.8

### ISSUE THREAD

**Issue by bollycanuk** [dbnschools/moodle-theme_fordson#94]
After upgrading from latest Moodle 3.7 to just released 3.8, the login dialog box flashes momentarily before being hidden by the slide show images. Switching between the slides displays the login dialog box briefly before being hidden again. Probably a Z index issue.

Custom login is set to Yes as is SlideShow in Fordson settings.

Deleting the Fordson folder from the Theme folder seems to be the only solution as Moodle defaults back to Boost.

**Comment by dbnschools** [comment]
Have you tried deleting cache?

**Comment by dbnschools** [comment]
The other solution would be to turn off the custom login page until a Moodle 3.8 version of Fordson is released.

**Comment by bollycanuk** [comment]
I just turned off the slideshow instead.

**Comment by dbnschools** [comment]
The 3.8 Version of Fordson fixes this.
