### ISSUE TITLE
Invalid param AJAX error on admin pages

### ISSUE THREAD

**Issue by DavidVogel-NC** [dbnschools/moodle-theme_fordson#97]
I just installed Fordson on several sites using Moodle 3.8. It's working fine on most of them, but on one of them every time an admin page loads with Fordson as the active theme I get this error: 

Invalid parameter value detected
File: /lib/externallib.php
Line: 332
Missing required key in single structure: year
Error code: invalidparameter
* line 332 of /lib/externallib.php: invalid_parameter_exception thrown
* line 223 of /lib/externallib.php: call to external_api::validate_parameters()
* line 79 of /lib/ajax/service.php: call to external_api::call_external_function()

I assume Fordson is running some sort of AJAX call on admin pages which is returning unexpected params?

**Comment by DavidVogel-NC** [comment]
Clearing theme caches did not help. The error does not occur with Boost. The site is running Moodle 3.8+ (Build: 20191212), and I'm using the latest Fordson v3.8 release 1.2 which I just downloaded today.

**Comment by dbnschools** [comment]
I would suggest you review what is different on the site having issues over the other ones that function normally.  I cannot reproduce this issue and it is odd that it doesn't occur on your other sites.

**Comment by marinaglancy** [comment]
Hello. This happens on all pages that have layout columns2.php , for example "admin" and "coursecategory". They forgot to set the $hascourseblocks variable and the block slider does not show.

To reproduce:
- Add "Calendar" block to the site home page and configure it to display on all pages.
- Go to the "Site administration" page - you will get the AJAX exception

On other pages there is a block slider that displays all blocks, on admin pages it is missing. The javascript for the calendar block is loaded on the page but the html is not rendered

**Comment by jtsafran** [comment]
Also want to add for anyone that comes across this error but is using Boost and are seeing it in the grader (as I did when googling): https://tracker.moodle.org/browse/MDL-73491

The work around in either case here is to set the offending block_calendar to display on "Any course page" or "Any type of course main page" instead of "Any page".
